/**
 * Download and optimize attorney headshots from parsed data
 * Run with: npx tsx scripts/download-attorney-headshots.ts
 */

import fs from 'fs/promises'
import { existsSync } from 'fs'
import path from 'path'
import axios from 'axios'
import sharp from 'sharp'
import process from 'node:process'

interface ParsedAttorney {
  id: string
  name: string
  imageUrl: string
}

async function downloadImage(url: string, outputPath: string): Promise<void> {
  const response = await axios.get(url, {
    responseType: 'arraybuffer',
    timeout: 30000,
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    },
  })
  await fs.writeFile(outputPath, response.data)
}

async function optimizeToWebP(inputPath: string, outputDir: string, slug: string): Promise<void> {
  const image = sharp(inputPath)
  const metadata = await image.metadata()
  
  console.log(`  📐 Original: ${metadata.width}x${metadata.height} (${metadata.format})`)
  
  // Generate multiple sizes for responsive images
  const sizes = [
    { width: 400, suffix: '' },      // Default size for cards/lists
    { width: 800, suffix: '@2x' },   // Retina display
    { width: 200, suffix: '-thumb' }, // Thumbnail
  ]
  
  for (const size of sizes) {
    const outputPath = path.join(outputDir, `${slug}${size.suffix}.webp`)
    
    await image
      .clone()
      .resize(size.width, null, {
        fit: 'cover',
        position: 'top',
        withoutEnlargement: true,
      })
      .webp({ quality: 85, effort: 6 })
      .toFile(outputPath)
    
    const stats = await fs.stat(outputPath)
    console.log(`  ✅ ${slug}${size.suffix}.webp (${size.width}px, ${(stats.size / 1024).toFixed(1)}KB)`)
  }
}

async function main() {
  // Load parsed attorney data
  const dataPath = path.resolve('src/lib/data/attorneys-parsed.ts')
  if (!existsSync(dataPath)) {
    console.error('❌ attorneys-parsed.ts not found. Run parse-attorney-bios.ts first.')
    process.exit(1)
  }
  
  // Read and parse the TypeScript file to extract attorney data
  const content = await fs.readFile(dataPath, 'utf8')
  const jsonMatch = content.match(/export const attorneys: ParsedAttorney\[\] = (\[[\s\S]*\])/)
  
  if (!jsonMatch) {
    console.error('❌ Could not parse attorney data from attorneys-parsed.ts')
    process.exit(1)
  }
  
  const attorneys: ParsedAttorney[] = JSON.parse(jsonMatch[1])
  
  console.log(`📸 Found ${attorneys.length} attorneys with photos\n`)
  
  // Create output directories
  const tempDir = path.resolve('scripts/output/attorney-photos-temp')
  const outputDir = path.resolve('public/assets/attorneys')
  
  await fs.mkdir(tempDir, { recursive: true })
  await fs.mkdir(outputDir, { recursive: true })
  
  let successCount = 0
  let errorCount = 0
  
  for (let i = 0; i < attorneys.length; i++) {
    const attorney = attorneys[i]
    const slug = attorney.id
    
    if (!attorney.imageUrl) {
      console.log(`[${i + 1}/${attorneys.length}] ⚠️  ${attorney.name} - No image URL`)
      errorCount++
      continue
    }
    
    try {
      console.log(`[${i + 1}/${attorneys.length}] Downloading ${attorney.name}...`)
      
      // Download original
      const tempPath = path.join(tempDir, `${slug}-original.tmp`)
      await downloadImage(attorney.imageUrl, tempPath)
      
      // Optimize and convert to WebP
      await optimizeToWebP(tempPath, outputDir, slug)
      
      // Clean up temp file
      await fs.unlink(tempPath)
      
      successCount++
      
      // Rate limiting - be nice to the server
      if (i < attorneys.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 500))
      }
    } catch (error) {
      console.error(`  ❌ Error processing ${attorney.name}:`, (error as Error).message)
      errorCount++
    }
  }
  
  // Clean up temp directory
  try {
    await fs.rmdir(tempDir)
  } catch (e) {
    // Ignore if not empty
  }
  
  console.log(`\n✨ Download complete!`)
  console.log(`   Success: ${successCount}`)
  console.log(`   Errors: ${errorCount}`)
  console.log(`\n📁 Photos saved to: ${outputDir}`)
  console.log(`\n📊 Generated files per attorney:`)
  console.log(`   - {slug}.webp (400px) - Default`)
  console.log(`   - {slug}@2x.webp (800px) - Retina`)
  console.log(`   - {slug}-thumb.webp (200px) - Thumbnail`)
  
  // Generate image mapping file
  const imageMap = attorneys
    .filter(a => a.imageUrl)
    .map(a => ({
      id: a.id,
      name: a.name,
      images: {
        default: `/assets/attorneys/${a.id}.webp`,
        retina: `/assets/attorneys/${a.id}@2x.webp`,
        thumb: `/assets/attorneys/${a.id}-thumb.webp`,
      },
    }))
  
  const mapContent = `/**
 * Attorney headshot image mappings
 * Auto-generated by scripts/download-attorney-headshots.ts
 * DO NOT EDIT MANUALLY
 */

export interface AttorneyImage {
  id: string
  name: string
  images: {
    default: string
    retina: string
    thumb: string
  }
}

export const attorneyImages: AttorneyImage[] = ${JSON.stringify(imageMap, null, 2)}

export function getAttorneyImage(id: string): AttorneyImage | undefined {
  return attorneyImages.find(img => img.id === id)
}
`
  
  const mapPath = path.resolve('src/lib/data/attorney-images.ts')
  await fs.writeFile(mapPath, mapContent, 'utf8')
  console.log(`\n📝 Image mapping saved to: ${mapPath}`)
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
