/**
 * Generate `src/lib/data/attorney-extras.ts` from `scraped-content/attorneys.json`.
 *
 * Purpose:
 * - Ensure attorney bio pages include all scraped sections, without editing the huge
 *   generated `src/lib/data/attorneys.ts` directly.
 *
 * Strategy:
 * - Match scraped entries to master attorney records by normalized name.
 * - Extract key headings into: representativeMatters, awards, education, barAdmissions, beyondOffice.
 * - Only store data that is non-empty.
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import type { Attorney, Education } from '../src/lib/types'
import { attorneys as masterAttorneys } from '../src/lib/data/attorneys'

type ScrapedSection =
  | {
      heading: string
      content: Array<
        | string
        | {
            type: 'list'
            items: string[]
          }
      >
    }

type ScrapedAttorney = {
  name: string
  title?: string
  email?: string
  phone?: string
  image?: string
  bio?: ScrapedSection[]
  practiceAreas?: string[]
  education?: string[]
  barAdmissions?: string[]
}

function normName(name: string) {
  return name
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function flattenSectionContent(section: ScrapedSection): string[] {
  const out: string[] = []
  for (const item of section.content ?? []) {
    if (typeof item === 'string') {
      const t = item.trim()
      if (t) out.push(t)
    } else if (item && typeof item === 'object' && item.type === 'list') {
      for (const li of item.items ?? []) {
        const t = String(li).trim()
        if (t) out.push(t)
      }
    }
  }
  return out
}

function pickSections(sections: ScrapedSection[] = []) {
  const rep: string[] = []
  const awards: string[] = []
  const beyond: string[] = []

  for (const s of sections) {
    const h = (s.heading || '').toLowerCase()
    const items = flattenSectionContent(s)
    if (items.length === 0) continue

    if (h.includes('representative matters')) rep.push(...items)
    else if (h.includes('awards') || h.includes('recognition')) awards.push(...items)
    else if (h.includes('beyond') || h.includes('outside') || h.includes('personal')) beyond.push(...items)
  }

  return {
    representativeMatters: Array.from(new Set(rep)),
    awards: Array.from(new Set(awards)),
    beyondOffice: beyond.join('\n\n').trim(),
  }
}

function toEducation(value: unknown): Education[] {
  if (!Array.isArray(value)) return []
  return value
    .map((v) => (typeof v === 'string' ? v.trim() : ''))
    .filter(Boolean)
    .map((institution) => ({
      institution,
      degree: '',
      year: '',
    }))
}

function toStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return []
  return value.map(v => (typeof v === 'string' ? v.trim() : '')).filter(Boolean)
}

async function main() {
  const root = process.cwd()
  const inputPath = path.join(root, 'scraped-content', 'attorneys.json')
  const outputPath = path.join(root, 'src', 'lib', 'data', 'attorney-extras.ts')

  const scrapedRaw = await fs.readFile(inputPath, 'utf8')
  const scraped = JSON.parse(scrapedRaw) as ScrapedAttorney[]

  const masterByNorm = new Map<string, Attorney>()
  for (const a of masterAttorneys) {
    masterByNorm.set(normName(a.name), a)
  }

  const extras: Record<string, any> = {}

  for (const s of scraped) {
    if (!s?.name || s.name === 'No Results Found') continue
    const match = masterByNorm.get(normName(s.name))
    if (!match) continue

    const picked = pickSections(s.bio ?? [])
    const education = toEducation(s.education)
    const barAdmissions = toStringArray(s.barAdmissions)

    const out: Record<string, unknown> = {}
    if (picked.representativeMatters.length > 0) out.representativeMatters = picked.representativeMatters
    if (picked.awards.length > 0) out.awards = picked.awards
    if (picked.beyondOffice) out.beyondOffice = picked.beyondOffice
    if (education.length > 0) out.education = education
    if (barAdmissions.length > 0) out.barAdmissions = barAdmissions

    if (Object.keys(out).length > 0) extras[match.id] = out
  }

  const file = `/**
 * Attorney extras (id -> supplemental fields) sourced from scraped bios.
 *
 * Auto-generated by \`scripts/generate-attorney-extras.ts\`.
 * Do not edit by hand.
 */

import type { Attorney } from '@/lib/types'

export type AttorneyExtras = Partial<
  Pick<Attorney, 'representativeMatters' | 'awards' | 'barAdmissions' | 'education' | 'beyondOffice'>
>

export const attorneyExtrasById: Record<string, AttorneyExtras> = ${JSON.stringify(extras, null, 2)} as const
`

  await fs.writeFile(outputPath, file, 'utf8')
  // eslint-disable-next-line no-console
  console.log(`✓ Wrote ${outputPath} (${Object.keys(extras).length} attorneys with extras)`)
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err)
  process.exit(1)
})

