/**
 * Attorney headshot image mappings
 * Auto-generated by scripts/download-attorney-headshots.ts
 * DO NOT EDIT MANUALLY
 */

export interface AttorneyImage {
  id: string
  name: string
  images: {
    default: string
    retina: string
    thumb: string
  }
}

export const attorneyImages: AttorneyImage[] = [
  {
    "id": "laura-k-binford",
    "name": "Laura K. Binford",
    "images": {
      "default": "/assets/attorneys/laura-k-binford.webp",
      "retina": "/assets/attorneys/laura-k-binford@2x.webp",
      "thumb": "/assets/attorneys/laura-k-binford-thumb.webp"
    }
  },
  {
    "id": "beau-browning",
    "name": "Beau Browning",
    "images": {
      "default": "/assets/attorneys/beau-browning.webp",
      "retina": "/assets/attorneys/beau-browning@2x.webp",
      "thumb": "/assets/attorneys/beau-browning-thumb.webp"
    }
  },
  {
    "id": "timothy-h-button",
    "name": "Timothy H. Button",
    "images": {
      "default": "/assets/attorneys/timothy-h-button.webp",
      "retina": "/assets/attorneys/timothy-h-button@2x.webp",
      "thumb": "/assets/attorneys/timothy-h-button-thumb.webp"
    }
  },
  {
    "id": "k-douglas-cook",
    "name": "K. Douglas Cook",
    "images": {
      "default": "/assets/attorneys/k-douglas-cook.webp",
      "retina": "/assets/attorneys/k-douglas-cook@2x.webp",
      "thumb": "/assets/attorneys/k-douglas-cook-thumb.webp"
    }
  },
  {
    "id": "john-l-egloff",
    "name": "John L. Egloff",
    "images": {
      "default": "/assets/attorneys/john-l-egloff.webp",
      "retina": "/assets/attorneys/john-l-egloff@2x.webp",
      "thumb": "/assets/attorneys/john-l-egloff-thumb.webp"
    }
  },
  {
    "id": "jeffrey-b-fecht",
    "name": "Jeffrey B. Fecht",
    "images": {
      "default": "/assets/attorneys/jeffrey-b-fecht.webp",
      "retina": "/assets/attorneys/jeffrey-b-fecht@2x.webp",
      "thumb": "/assets/attorneys/jeffrey-b-fecht-thumb.webp"
    }
  },
  {
    "id": "jaclyn-m-flint",
    "name": "Jaclyn M. Flint",
    "images": {
      "default": "/assets/attorneys/jaclyn-m-flint.webp",
      "retina": "/assets/attorneys/jaclyn-m-flint@2x.webp",
      "thumb": "/assets/attorneys/jaclyn-m-flint-thumb.webp"
    }
  },
  {
    "id": "kathleen-hart",
    "name": "Kathleen Hart",
    "images": {
      "default": "/assets/attorneys/kathleen-hart.webp",
      "retina": "/assets/attorneys/kathleen-hart@2x.webp",
      "thumb": "/assets/attorneys/kathleen-hart-thumb.webp"
    }
  },
  {
    "id": "eric-m-hylton",
    "name": "Eric M. Hylton",
    "images": {
      "default": "/assets/attorneys/eric-m-hylton.webp",
      "retina": "/assets/attorneys/eric-m-hylton@2x.webp",
      "thumb": "/assets/attorneys/eric-m-hylton-thumb.webp"
    }
  },
  {
    "id": "anthony-r-jost",
    "name": "Anthony R. Jost",
    "images": {
      "default": "/assets/attorneys/anthony-r-jost.webp",
      "retina": "/assets/attorneys/anthony-r-jost@2x.webp",
      "thumb": "/assets/attorneys/anthony-r-jost-thumb.webp"
    }
  },
  {
    "id": "james-w-riley-jr",
    "name": "James W. Riley Jr.",
    "images": {
      "default": "/assets/attorneys/james-w-riley-jr.webp",
      "retina": "/assets/attorneys/james-w-riley-jr@2x.webp",
      "thumb": "/assets/attorneys/james-w-riley-jr-thumb.webp"
    }
  },
  {
    "id": "ryan-l-leitch",
    "name": "Ryan L. Leitch",
    "images": {
      "default": "/assets/attorneys/ryan-l-leitch.webp",
      "retina": "/assets/attorneys/ryan-l-leitch@2x.webp",
      "thumb": "/assets/attorneys/ryan-l-leitch-thumb.webp"
    }
  },
  {
    "id": "lindsay-a-llewellyn",
    "name": "Lindsay A. Llewellyn",
    "images": {
      "default": "/assets/attorneys/lindsay-a-llewellyn.webp",
      "retina": "/assets/attorneys/lindsay-a-llewellyn@2x.webp",
      "thumb": "/assets/attorneys/lindsay-a-llewellyn-thumb.webp"
    }
  },
  {
    "id": "sarah-macgill-marr",
    "name": "Sarah MacGill Marr",
    "images": {
      "default": "/assets/attorneys/sarah-macgill-marr.webp",
      "retina": "/assets/attorneys/sarah-macgill-marr@2x.webp",
      "thumb": "/assets/attorneys/sarah-macgill-marr-thumb.webp"
    }
  },
  {
    "id": "anna-marvin",
    "name": "Anna K. Marvin",
    "images": {
      "default": "/assets/attorneys/anna-marvin.webp",
      "retina": "/assets/attorneys/anna-marvin@2x.webp",
      "thumb": "/assets/attorneys/anna-marvin-thumb.webp"
    }
  },
  {
    "id": "patrick-s-mccarney",
    "name": "Patrick S. McCarney",
    "images": {
      "default": "/assets/attorneys/patrick-s-mccarney.webp",
      "retina": "/assets/attorneys/patrick-s-mccarney@2x.webp",
      "thumb": "/assets/attorneys/patrick-s-mccarney-thumb.webp"
    }
  },
  {
    "id": "courtney-david-mills",
    "name": "Courtney David Mills",
    "images": {
      "default": "/assets/attorneys/courtney-david-mills.webp",
      "retina": "/assets/attorneys/courtney-david-mills@2x.webp",
      "thumb": "/assets/attorneys/courtney-david-mills-thumb.webp"
    }
  },
  {
    "id": "katie-r-osborne",
    "name": "Katie R. Osborne",
    "images": {
      "default": "/assets/attorneys/katie-r-osborne.webp",
      "retina": "/assets/attorneys/katie-r-osborne@2x.webp",
      "thumb": "/assets/attorneys/katie-r-osborne-thumb.webp"
    }
  },
  {
    "id": "laura-s-reed",
    "name": "Laura S. Reed",
    "images": {
      "default": "/assets/attorneys/laura-s-reed.webp",
      "retina": "/assets/attorneys/laura-s-reed@2x.webp",
      "thumb": "/assets/attorneys/laura-s-reed-thumb.webp"
    }
  },
  {
    "id": "katie-s-riles",
    "name": "Katie S. Riles",
    "images": {
      "default": "/assets/attorneys/katie-s-riles.webp",
      "retina": "/assets/attorneys/katie-s-riles@2x.webp",
      "thumb": "/assets/attorneys/katie-s-riles-thumb.webp"
    }
  },
  {
    "id": "raymond-t-seach",
    "name": "Raymond T. Seach",
    "images": {
      "default": "/assets/attorneys/raymond-t-seach.webp",
      "retina": "/assets/attorneys/raymond-t-seach@2x.webp",
      "thumb": "/assets/attorneys/raymond-t-seach-thumb.webp"
    }
  },
  {
    "id": "donald-s-smith",
    "name": "Donald S. Smith",
    "images": {
      "default": "/assets/attorneys/donald-s-smith.webp",
      "retina": "/assets/attorneys/donald-s-smith@2x.webp",
      "thumb": "/assets/attorneys/donald-s-smith-thumb.webp"
    }
  },
  {
    "id": "justin-o-sorrell",
    "name": "Justin O. Sorrell",
    "images": {
      "default": "/assets/attorneys/justin-o-sorrell.webp",
      "retina": "/assets/attorneys/justin-o-sorrell@2x.webp",
      "thumb": "/assets/attorneys/justin-o-sorrell-thumb.webp"
    }
  },
  {
    "id": "kevin-n-tharp",
    "name": "Kevin N. Tharp",
    "images": {
      "default": "/assets/attorneys/kevin-n-tharp.webp",
      "retina": "/assets/attorneys/kevin-n-tharp@2x.webp",
      "thumb": "/assets/attorneys/kevin-n-tharp-thumb.webp"
    }
  },
  {
    "id": "blair-r-vandivier",
    "name": "Blair R. Vandivier",
    "images": {
      "default": "/assets/attorneys/blair-r-vandivier.webp",
      "retina": "/assets/attorneys/blair-r-vandivier@2x.webp",
      "thumb": "/assets/attorneys/blair-r-vandivier-thumb.webp"
    }
  },
  {
    "id": "travis-r-watson",
    "name": "Travis R. Watson",
    "images": {
      "default": "/assets/attorneys/travis-r-watson.webp",
      "retina": "/assets/attorneys/travis-r-watson@2x.webp",
      "thumb": "/assets/attorneys/travis-r-watson-thumb.webp"
    }
  },
  {
    "id": "j-t-wynne",
    "name": "J.T. Wynne",
    "images": {
      "default": "/assets/attorneys/j-t-wynne.webp",
      "retina": "/assets/attorneys/j-t-wynne@2x.webp",
      "thumb": "/assets/attorneys/j-t-wynne-thumb.webp"
    }
  },
  {
    "id": "megan-s-young",
    "name": "Megan S. Young",
    "images": {
      "default": "/assets/attorneys/megan-s-young.webp",
      "retina": "/assets/attorneys/megan-s-young@2x.webp",
      "thumb": "/assets/attorneys/megan-s-young-thumb.webp"
    }
  }
]

export function getAttorneyImage(id: string): AttorneyImage | undefined {
  return attorneyImages.find(img => img.id === id)
}
