/**
 * Attorney extras (id -> supplemental fields) sourced from scraped bios.
 *
 * Auto-generated by `scripts/generate-attorney-extras-from-raw.ts`.
 * Do not edit by hand.
 */

import type { Attorney } from '@/lib/types'

export type AttorneyExtras = Partial<
  Pick<
    Attorney,
    | 'representativeMatters'
    | 'awards'
    | 'barAdmissions'
    | 'education'
    | 'beyondOffice'
    | 'assistant'
    | 'fax'
    | 'bioPdfUrl'
    | 'associations'
  >
>

export const attorneyExtrasById: Record<string, AttorneyExtras> = {
  "anna-marvin": {
    "assistant": {
      "name": "Beth A. Reis",
      "email": "breis@rbelaw.com"
    },
    "fax": "317-955-7154",
    "associations": [
      "Indiana State Bar Association"
    ],
    "barAdmissions": [
      "Indiana, 2024",
      "U.S. District Court for the Southern District of Indiana, 2025"
    ],
    "education": [
      {
        "institution": "Indiana University Maurer School of Law, JD, _cum laude_, 2024.",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University Bloomington, BS, Psychology; Certificate: Clinical Psychological Science, _highest distinction_, 2021.",
        "degree": "",
        "year": ""
      }
    ]
  },
  "anthony-r-jost": {
    "assistant": {
      "name": "Rhonda McClintic",
      "email": "RMcClintic@rbelaw.com"
    },
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/07/2024-Anthony-Jost-Bio.pdf",
    "associations": [
      "American Bar Association",
      "Defense Research Institute",
      "Defense Trial Counsel of Indiana",
      "Hendricks County Bar Association",
      "Illinois State Bar Association",
      "Indiana Bankers Association",
      "Indiana Mortgage Bankers Association",
      "Indiana State Bar Association, House of Delegates",
      "Indianapolis Bar Association"
    ],
    "representativeMatters": [
      "Represented multiple multi-billion dollar creditors in all aspects of bankruptcy proceedings.",
      "Defended at trial a number of lawsuits against trucking companies for claims involving personal injury and property damage.",
      "Prosecuted large mechanics lien and breach of construction contract claims on behalf of general contractors, seeking payment for construction products and services.",
      "Prosecuted claims on behalf of health-care providers in pursuing payment under service provider agreements and other contracts.",
      "Represented banking clients in preparing and negotiating loan documents and service agreements and in prosecuting claims associated with breaches under those documents and agreements.",
      "Negotiated and drafted finance, transactional and organizational documents for various clients.",
      "Successfully defended and tried lawsuits in commercial, real estate, employment and complex litigation matters on numerous occasions."
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Bankruptcy and Finance Law: 2026",
      "Bankruptcy and Creditor Debtor Rights / Insolvency and Reorganization Law: 2022 – present",
      "Commercial Litigation: 2026",
      "Litigation – Construction: 2026",
      "Litigation – Labor and Employment: 2026",
      "Indiana Super Lawyers, 2012 – 2021, 2023",
      "Business Litigation",
      "Bankruptcy, Business and Corporate",
      "Legal 500 Elite – Indianapolis",
      "Commercial Disputes, 2025",
      "Indianapolis Bar Foundation",
      "Distinguished Life Fellow, 2017",
      "Distinguished Fellow, 2006",
      "Boy Scouts of America",
      "Crossroads of America Council Silver Beaver Award, 2017",
      "District Award of Merit, 2011",
      "Scouter’s Key Award, 2014",
      "Cubmaster of the Year, Hou Koda District, 2015",
      "Hou Koda District Golden Feather Award, 2012",
      "Eagle Scout, May 17, 1984",
      "Delta Theta Phi. Notes Editor, Adelphia Law Journal",
      "Stanley K. Lacy Executive Leadership Series Class XXX"
    ],
    "barAdmissions": [
      "Indiana, 1993",
      "Illinois, 1994",
      "U.S. Seventh Circuit Court of Appeals",
      "U.S. District Court for the Northern District of Indiana",
      "U.S. District Court for the Southern District of Indiana",
      "U.S. District Court for the Central District of Illinois",
      "U.S. District Court for the Northern District of Illinois",
      "U.S. District Court for the Southern District of Illinois"
    ],
    "education": [
      {
        "institution": "Indiana University Maurer School of Law, JD, 1993",
        "degree": "",
        "year": ""
      },
      {
        "institution": "DePauw University, BA, _cum laude,_ 1990",
        "degree": "",
        "year": ""
      }
    ]
  },
  "beau-browning": {
    "assistant": {
      "name": "Lana Neligh",
      "email": "lneligh@rbelaw.com"
    },
    "fax": "317-955-7135",
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/08/Beau-Browning-Bio-08-27-25.pdf",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "Defense Trial Council of Indiana (DTCI)",
      "Indiana Rural Health Association",
      "Indiana Society for Healthcare Risk Management (ISHRM)"
    ],
    "barAdmissions": [
      "Indiana, 2015",
      "U.S. District Court for the Northern District of Indiana, 2015",
      "U.S. District Court for the Southern District of Indiana, 2015",
      "Supreme Court of the United States, 2025"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 2015, _cum laude_",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Ball State University, BS, Political Science and Economics — double major, 2012, _cum laude_",
        "degree": "",
        "year": ""
      }
    ]
  },
  "blair-r-vandivier": {
    "associations": [
      "Indiana State Bar Association"
    ],
    "representativeMatters": [
      "Assisted numerous secured lenders in the negotiation and closing of commercial lending transactions involving manufacturing, construction, commercial leasing and real estate matters.",
      "Assisted buyers and sellers of businesses in the manufacturing and services industries in the successful completion of transactions involving the transfer of ownership.",
      "Provided counsel on an ongoing basis to business managers and owners in the challenges associated with the day-to-day operation of their businesses."
    ],
    "awards": [
      "Martindale-Hubbell AV rated",
      "Recipient, American Jurisprudence Award in Estates",
      "Listed in Who’s Who in American Law"
    ],
    "barAdmissions": [
      "Indiana, 1978",
      "U.S. District Court for the Southern District of Indiana, 1978"
    ],
    "education": [
      {
        "institution": "Indiana University Maurer School of Law, JD, _cum laude,_ 1981",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Butler University, BS, Administration and Economics (Dual Major) with _Highest Honors_ in Economics, _Magna Cum Laude_, 1978",
        "degree": "",
        "year": ""
      }
    ]
  },
  "courtney-david-mills": {
    "assistant": {
      "name": "Julie A. Adams",
      "email": "jadams@rbelaw.com"
    },
    "fax": "317-955-2154",
    "associations": [
      "Indianapolis Bar Association",
      "Indiana State Bar Association",
      "Defense Trial Counsel of Indiana",
      "Defense Research Institute"
    ],
    "beyondOffice": "Courtney is actively involved in animal rescue groups and volunteers with ASPCA. He enjoys hiking, camping and wilderness survival.",
    "representativeMatters": [
      "Successfully obtained a dismissal for a long-term care facility based on a violation of the statute of limitations for a non-qualified health care provider subject to the Professional Services Statute.",
      "Obtained a favorable reversal in favor of a physician pursuant to Indiana’s bright-line rule prohibiting untimely materials submitted in summary judgment proceedings.",
      "Successfully obtained a dismissal for an athletic trainer seeking protection under Indiana’s Medical Malpractice Act in a case of first impression regarding whether Athletic Trainers are considered Health-Care Providers under Indiana’s Medical Malpractice Act.",
      "Successfully obtained a dismissal for a physician seeking immunity under Indiana’s Strategic Lawsuit Against Public Participation law (“SLAPP” law) in the first SLAPP case brought before the Indiana Supreme Court.",
      "Successfully obtained an early case dismissal for a physician who was sued in District Court for reporting suspected child abuse to DCS. The complaint alleged a conspiracy to violate a mother’s constitutional right of family integrity by causing DCS to separate the family."
    ],
    "awards": [
      "Best Lawyers: Ones To Watch®",
      "Insurance Law: 2022 – present",
      "Medical Malpractice Law — Defendants: 2022 – present",
      "Indiana Super Lawyers Rising Star",
      "Medical Malpractice — Defense: 2020 – present",
      "National Moot Court Competition",
      "Competitor, 2014",
      "Indiana University Robert H. McKinney School of Law",
      "Order of the Barristers, 2013",
      "Indiana Paralegal Association",
      "Board Member of the Year, 2007",
      "Paralegal of the Year, 2008",
      "Leadership Award, 2010",
      "Boy Scouts of America, Eagle Scout, 1998"
    ],
    "barAdmissions": [
      "Indiana, 2015",
      "U.S. District Court for the Northern District of Indiana, 2015",
      "U.S. District Court for the Southern District of Indiana, 2015"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 2015",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University Indianapolis, BA, Political Science, 2004",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University Indianapolis, Paralegal Studies, 2002",
        "degree": "",
        "year": ""
      }
    ]
  },
  "donald-s-smith": {
    "assistant": {
      "name": "Nicole Poletika",
      "email": "npoletika@rbelaw.com"
    },
    "fax": "317-955-7106",
    "associations": [
      "Chair, Labor and Employment Law Section, 1993",
      "Member, Labor and Employment Law Section, 1981 – present"
    ],
    "beyondOffice": "Don and his wife, Debbie, are the proud parents of three sons, and the very proud grandparents of six grandchildren. All three of their sons are medical doctors after attending medical school at Indiana University. Don remains a huge sports fanatic, with special interests in his Indianapolis Colts, Indiana Pacers, Indianapolis Indians, and Chicago Cubs (with whom he has played in two fantasy camps).\n\nDuring the college football season, Don particularly roots for DePauw, Miami (Fla.), and Alabama, teams he “adopted” as a result of where his sons attended school. Don is an avid golfer who is constantly in search of the “perfect swing.”",
    "representativeMatters": [
      "Prosecuted and defended numerous requests for temporary and permanent injunctions in non-compete cases on behalf of employers.",
      "Defended an insurance company in employment discrimination case that set the standard for determining whether an insurance agent is an independent contractor: _Knight v. United Farm Bureau Mut. Ins. Co., Inc.,_ 950 F.2d 377 (7th Cir. 1991).",
      "Defended county employer at trial and on appeal against wrongful discharge claim: _Moulton v. Vigo Co.,_ 150 F.3d 801 (7th Cir. 1998).",
      "Represented employer in a religious discrimination case, in which employee unsuccessfully sought court intervention permitting employee to use the phrase “Have a blessed day” in the workplace: _Anderson v. U.S.F. Logistics_, 274 F.3d. 470 (7th Cir. 2001).",
      "Represented employer in a wage case, in which the Indiana Court of Appeals reversed the trial court’s award of vacation pay to the employee, and enforced the employer’s written policy that vacation pay was not earned until the employee’s anniversary date: _Damon Corp. v. Estes_, 750 N.E.2d 891 (Ind. Ct. App. 2001).",
      "Represented employer hospital in a worker’s compensation case, in which the Indiana Supreme Court ruled that the Worker’s Compensation Board lacked the statutory authority to award interest on worker’s compensation benefits, including overdue medical bills: _Christopher R. Brown, DDS, Inc. v. Decatur Co. Memorial Hospital, Inc.,_ 892 N.E.2d 642 (Ind. 2008).",
      "Defended employer in a class action in a wage and hour case: _Artis v. First Revenue Assurance, LLC_, (1:09-cv-01555, S. D. Ind. 2009)."
    ],
    "awards": [
      "The Best Lawyers in America®: 2022 – present",
      "Employment Law — Management",
      "Litigation — Labor and Employment",
      "Workers’ Compensation Law — Employers",
      "The Best Lawyers in America® “Lawyer of the Year”\\* Indianapolis: 2023 & 2025",
      "Indiana Super Lawyers, 2004 – 2006 and 2009 – present",
      "Employment and Labor",
      "Martindale-Hubble AV Preeminent Rated",
      "First Baptist Athletics Hall of Fame inductee, 2006",
      "Don was inducted into the First Baptist Athletics Hall of Fame after coaching basketball there for years. He continues to referee youth basketball. First Baptist Athletics’ motto is “The Place for Good Sports.”"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, _cum laude,_ 1981",
        "degree": "",
        "year": ""
      },
      {
        "institution": "DePauw University, BA, Communications, _cum laude,_ 1978",
        "degree": "",
        "year": ""
      }
    ]
  },
  "eric-m-hylton": {
    "assistant": {
      "name": "Nicole Poletika",
      "email": "npoletika@rbelaw.com"
    },
    "fax": "317-955-7158",
    "associations": [
      "Indianapolis Bar Association",
      "Labor and Employment Law Section",
      "Indiana State Bar Association"
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Education Law: 2013 – Present",
      "Best Lawyers _Lawyer of the Year_, Indianapolis",
      "Education Law: 2016, 2023, and 2026"
    ],
    "barAdmissions": [
      "Indiana, 1997",
      "U.S. District Court for the Southern District of Indiana, 1997"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, _magna cum laude,_ 1997",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University Kelley School of Business, BS, Marketing and Management, 1993",
        "degree": "",
        "year": ""
      }
    ]
  },
  "j-t-wynne": {
    "assistant": {
      "name": "Rhonda L. McClintic",
      "email": "rmcclintic@rbelaw.com"
    },
    "fax": "317-955-2156",
    "associations": [
      "Indiana State Bar Association",
      "Young Lawyers Division"
    ],
    "barAdmissions": [
      "Indiana, 2024"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 2023",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Skidmore College, BS, Business and History, 2020",
        "degree": "",
        "year": ""
      }
    ]
  },
  "jaclyn-m-flint": {
    "assistant": {
      "name": "Nicole Poletika",
      "email": "npoletika@rbelaw.com"
    },
    "fax": "317-955-7159",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "Sports and Entertainment Law Section",
      "Intellectual Property Section",
      "Young Lawyers Division, 2015 – Present",
      "Women and the Law Division, 2015 – Present"
    ],
    "barAdmissions": [
      "Indiana, 2015",
      "U.S. District Court, Northern District of Indiana, 2015",
      "U.S. District Court, Southern District of Indiana, 2015",
      "Seventh Circuit Court of Appeals, 2020",
      "U.S. Supreme Court, 2023"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, Intellectual Property Law Graduate Certificate and JD, _summa cum laude_ _,_ 2015",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Purdue University, BA, Communication, _with Highest Distinction_, 2012",
        "degree": "",
        "year": ""
      }
    ]
  },
  "james-w-riley-jr": {
    "assistant": {
      "name": "Beth A. Reis",
      "email": "breis@rbelaw.com"
    },
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/12/James-Riley-Jr-Bio-12-18-25.pdf",
    "associations": [
      "American Arbitration Association — Consumer Mediation Panel",
      "National Arbitration and Mediation — Indiana Panel",
      "American Bar Association",
      "House of Delegates, 2005 – 2006",
      "Indiana State Bar Association",
      "President, 2005 – 2006",
      "Chair, House of Delegates, 2003",
      "Board of Governors, 1997 – 1999, 2001 – 2003",
      "Fellow: Indianapolis, Indiana (Board of Directors, 2004) and American Bar Foundations",
      "Federal Bar Association",
      "Southern District Local Rules Advisory Committee, Seventh Circuit Bar Association",
      "Indianapolis Bar Association",
      "Board of Managers, 11th District Representative, 1997 –1999",
      "Defense Trial Counsel of Indiana",
      "Board of Directors, 1996 – 1999",
      "Federation of Defense and Corporate Counsel",
      "Defense Research Institute"
    ],
    "representativeMatters": [
      "Defended owner from claims in excess of 70 million dollars relating to construction accident property damage and prosecuted related insurance coverage action.",
      "Represented manufacturers in catastrophic injury products liability actions to defense verdicts.",
      "Represented manufacturer in multiple fatality wrongful death products liability action to defense verdict.",
      "Represented telecommunication company in trademark and patent infringement actions.",
      "Represented generic drug manufacturers in ANDA patent infringement actions.",
      "Represented bank in Directors and Officers liability and insurance coverage actions.",
      "Represented retailer in commercial action against banks."
    ],
    "awards": [
      "The Best Lawyers In America®",
      "Arbitration: 2024 – present",
      "Business Organizations (including LLCs and Partnerships): 2026",
      "Commercial Litigation: 2024 – present",
      "[Martindale-Hubbell AV Preeminent Rated](https://www.martindale.com/attorney/mr-james-w-riley-jr-980366/)",
      "[Indiana Super Lawyers, 2004 – present](https://www.superlawyers.com/indiana/lawyer/James-W-Riley-Jr/5aadfc8c-5faf-485e-9d6e-73c46f85d93c.html)",
      "Business Litigation",
      "Sagamore of the Wabash Awarded by Indiana Governor Mitchell E. Daniels, October 4, 2006",
      "Indiana State Bar Association",
      "Presidential Citations, 1999, 2000, 2003, 2007, 2012, and 2016",
      "Litigation Section Civility Award, October 17, 2013"
    ],
    "barAdmissions": [
      "Indiana, 1972",
      "U.S. Supreme Court, 1975",
      "U.S. Seventh Circuit Court of Appeals, 1973",
      "U.S. District Court for the Northern District of Indiana, 1972",
      "U.S. District Court for the Southern District of Indiana, 1972"
    ],
    "education": [
      {
        "institution": "University of Michigan, JD, 1972",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Purdue University, BS, 1969",
        "degree": "",
        "year": ""
      }
    ]
  },
  "jeffrey-b-fecht": {
    "assistant": {
      "name": "Rhonda L. McClintic",
      "email": "rmcclintic@rbelaw.com"
    },
    "fax": "317-955-7163",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "Defense Trial Counsel of Indiana",
      "Defense Research Institute"
    ],
    "representativeMatters": [
      "Represented insurers in action where the Indiana Court of Appeals affirmed the trial court’s grant of summary judgment in favor of the insurers against a city seeking insurance coverage for costs related to an underlying USEPA action demanding that the city upgrade its sewer system to prevent future combined sewer overflows.",
      "Represented insurer in multi-million-dollar environmental coverage action filed by insured. Obtained dismissal of Indiana action in favor of another coverage action filed by the insurer in a more favorable jurisdiction.",
      "Represented insurer in multi-million-dollar environmental coverage claim by insured relating to contamination at neighboring facility. Case settled on terms favorable to client prior to trial.",
      "Defended paving contractor against Clean Water Act violations alleged by EPA and IDEM at multiple sites. Claims resolved on terms favorable to client without imposition of civil penalties.",
      "Defended municipality in IDEM environmental cleanup arising from petroleum spill. Claim resolved favorably with majority of costs reimbursed by Indiana’s Environmental Liability Trust Fund.",
      "Represented excess insurer in claim for underinsured motorists coverage relating to serious bodily injury. Court of Appeals determined that policy did not provide coverage.",
      "Defended real estate developer against purchaser’s claims relating to alleged defects in construction of warehouse. Case settled on terms favorable to client prior to trial.",
      "Defended manufacturer in premises liability claim by employee of contractor injured during remodeling project. Obtained summary judgment in favor of client.",
      "Defended property owners in multiple premises liability claims relating to toxic mold. Cases settled on terms favorable to client prior to trial.",
      "Defended distributor of dietary supplement in product liability claim by seriously injured consumer. Case settled on terms favorable to client prior to trial.",
      "Defended restaurant owner in wrongful death dram shop action. Case settled on terms favorable to client prior to trial."
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Commercial Litigation: 2025 – present",
      "Insurance Law: 2023 – present",
      "Litigation — Insurance: 2023– present",
      "Indiana Super Lawyers",
      "Insurance Coverage: 2014 – present",
      "Indiana Super Lawyers Rising Star",
      "Insurance Coverage: 2012 – 2013"
    ],
    "education": [
      {
        "institution": "Vanderbilt University, JD, 1998",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Vanderbilt University, BA, _cum laude,_ 1995",
        "degree": "",
        "year": ""
      }
    ]
  },
  "john-l-egloff": {
    "assistant": {
      "name": "Nikki L. Viau",
      "email": "nviau@rbelaw.com"
    },
    "fax": "317-955-7145",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "American Bar Association, Business Law Section and Law Practice Management Section"
    ],
    "representativeMatters": [
      "Representation of business owners in merger and acquisition transactions ranging in size from a few hundred thousand dollars to $300 million.",
      "Representation of borrowers in various business financing transactions ranging from $50,000 to $25 million.",
      "Representation of shareholders/owners in numerous shareholder/owner disputes in companies ranging in size from $250,000 to $30 million in value.",
      "Representation of entrepreneurs and businesses in private placement transactions of up to $25 million.",
      "Assisted client in recovery of $1 million from the vendor of defective manufacturing technology.",
      "Representation of numerous physicians in the negotiation of employment agreements with hospitals and medical groups, and in the sale of physician practices.",
      "Ongoing representation of national retailer in lease negotiations and related matters involving more than 100 shopping centers in six states.",
      "Representation of landlords of office and retail space in various leasing matters."
    ],
    "awards": [
      "**The Best Lawyers in America®**",
      "Business Organizations – including LLCs and Partnerships: 2025 – present",
      "Employee Benefits (ERISA) Law: 1991 – 2024",
      "Real Estate Law: 1991 – present",
      "Indiana Super Lawyers — 2004 – present",
      "Business & Corporate",
      "Real Estate",
      "Employee Benefits",
      "Martindale-Hubbell AV Rated",
      "Martindale-Hubbell® Peer Review Ratings™ are the gold standard in attorney ratings. An “AV” rating is the most prestigious rating.",
      "Indiana State Bar Association Presidential Citation: 2004",
      "Who’s Who in American Law",
      "Order of the Coif — 1978"
    ],
    "barAdmissions": [
      "Indiana, 1978",
      "U.S. District Court, Northern District of Indiana",
      "U.S. District Court, Southern District of Indiana",
      "U.S. Court of Appeals for the Seventh Circuit",
      "U.S. Supreme Court"
    ],
    "education": [
      {
        "institution": "Indiana University Maurer School of Law, JD, _magna cum laude,_ 1978",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Michigan State University, BA, Humanities/Pre-Law, _with honors,_ 1975",
        "degree": "",
        "year": ""
      }
    ]
  },
  "justin-o-sorrell": {
    "assistant": {
      "name": "Penny A. Curtis",
      "email": "pcurtis@rbelaw.com"
    },
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2024/01/2024-Justin-Sorrell-Bio-pdf.pdf",
    "representativeMatters": [
      "Defended adverse party’s appeal of trial court’s entry of summary judgment in favor of client. Court of Appeals clarified circumstances under which private organization is not liable for alleged actions of a purported subsidiary organization. _White et al. v. The American Legion, Inc. et al._, 24A-CT-1043 (Ind. Ct. App. 2025) (publication information not yet available).",
      "Prosecuted appeal of denial of motion to dismiss claims for intentional infliction of emotional distress. Won reversal of trial court’s decision and dismissal of emotional distress claims. Court of Appeals clarified that, under Indiana law, non-dependent children are not proper parties to seek damages, and intentional infliction of emotional distress claims are not permitted under Indiana’s General Wrongful Death Statute: _Edna Martin Christian Center, Inc. et al. v. Smith_, 202 N.E.3d 1118 (Ind. Ct. App. 2023).",
      "Prosecuted appeal of denial of summary judgment sought on behalf of truck leasing company. Won partial reversal of trial court’s decision, and entry of summary judgment on one of the plaintiffs’ claims.: _Penske Truck Leasing Co., L.P. v. McGrath_, 157 N.E.3d 5 (Ind. Ct. App. 2020).",
      "Defended adverse party’s appeal of entry of summary judgment and dismissal of lawsuit in favor of truck leasing company and truck driver: _White v. Holland_, 19A-CT-967 (Ind. Ct. App. 2019) (memorandum decision), _trans. denied_.",
      "Prosecuted appeal of punitive damages award entered in favor of adverse party. Won reversal of punitive damages award: _West v. J. Greg Allen Builder, Inc._, 92 N.E.3d 634 (Ind. Ct. App. 2017), _trans. denied_.",
      "Prosecuted appeal of summary judgment entered in favor of adverse party. Won reversal of summary judgment and remand for new trial in favor of patron: _Miller v. Rosehill Hotels, LLC_, 45 N.E.3d 15 (Ind. Ct. App. 2015)."
    ],
    "awards": [
      "Best Lawyers in America®",
      "Commercial Litigation: 2026",
      "Litigation — Labor and Employment: 2026",
      "Real Estate Law: 2026",
      "Best Lawyers: Ones to Watch®: 2021 – 2025",
      "Commercial Litigation",
      "Labor and Employment Law — Management",
      "Litigation — Labor and Employment",
      "Real Estate Law",
      "Indiana Super Lawyers Rising Star: 2020 – 2024",
      "General Litigation",
      "Indianapolis Bar Association",
      "Young Lawyers Division Distinguished Leadership Award, 2018"
    ]
  },
  "k-douglas-cook": {
    "fax": "317-955-7159",
    "education": [
      {
        "institution": "• Indiana University Indianapolis McKinney School of Law, JD, _Magna Cum Laude_, 1986",
        "degree": "",
        "year": ""
      },
      {
        "institution": "• Ball State University, BS, _Cum Laude,_ 1979",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[0](https://rbelaw.com/our-team/attorneys/k-douglas-cook/#)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[1](https://rbelaw.com/our-team/attorneys/k-douglas-cook/#)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[2](https://rbelaw.com/our-team/attorneys/k-douglas-cook/#)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[3](https://rbelaw.com/our-team/attorneys/k-douglas-cook/#)",
        "degree": "",
        "year": ""
      }
    ]
  },
  "kathleen-hart": {
    "assistant": {
      "name": "Rebecca D. Keever",
      "email": "bkeever@rbelaw.com"
    },
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/12/Kathleen-Hart-Bio-12-03-2025.pdf",
    "associations": [
      "Indianapolis Bar Association",
      "Member, 1994 – present",
      "Board Member, 2014 – 2015 and 2011 – 2012",
      "Counsel to the Board, 2013",
      "Standing Committee on Professionalism Co-Chair, 2010",
      "Federal Bar Association, Indianapolis Chapter",
      "President, 2008 – 2009",
      "Officer/Executive Committee Member, 2002 – 2010",
      "Sagamore American Inn of Court",
      "Executive Committee/Barrister, 2000 – 2010"
    ],
    "representativeMatters": [
      "Represented conglomerate of multi-state, multi-million-dollar businesses in defending against lawsuit brought by estate of a founding member attempting to take control of businesses; ultimately resolved dispute with divestiture of estate’s ownership in all businesses",
      "Represented trustees of multi-million-dollar estate involving varied real estate parcels to be divided among multiple heirs; defeated all allegations of breach of fiduciary duty and prevailed in trial court judgment for clients",
      "Represented different business clients in separate embezzlement cases, including judgments against offenders, coordination of criminal prosecution, seizure of assets, collection measures against offenders, and pursuit of malpractice action with client-favorable settlement against accounting firm whose annual reviews failed to meet GAAP standards",
      "Represented longstanding manufacturing client in issuing first industry-standard safety warning system for products by researching, analyzing, and drafting product warning labels compliant with ANSI standards in coordination with engineering employees",
      "Represented national companies in defending against collective action brought under FLSA for wage misclassification and underpayment; ultimately resolved dispute by capitalizing on rare opportunity to warrant nominal client involvement",
      "Regularly represent multiple business and individual clients in interpreting, negotiating, and drafting various contracts or successful termination of contracts, including executive/management employment agreements, compensation plans, separation/severance agreements, change-in-control, confidentiality/non-disclosure, non-competition agreements, operating agreements, partnership agreements, and bylaws, as well as third-party contracts involving franchised transactions, real estate, joint venture, commerce, intellectual property, patent license, franchise, retail, rental, supply, manufacturing, warranty, regulatory, and consumer-related matters",
      "Regularly represent clients to obtain or defeat injunctive relief being sought and to otherwise resolve lawsuits involving non-competition claims, including those involving medical/physician, executive/management, shareholder/founders, sales, industrial/manufacturing, and financial/banking",
      "Regularly assist multiple business clients with formation of entities, conversion of entities, governing documents, corporate governance, legal compliance issues, and preparation of private placement memoranda",
      "Regularly counsel numerous businesses who hire employees subject to non-compete or other restrictive covenants, and/or employees who need legal analysis of enforceability or compliance respecting prospective employment",
      "Regularly counsel and assist clients in obtaining certification for minority business enterprise (MBE), woman-owned business enterprise (WBE), disadvantaged business enterprise (DBE), and service-disabled veteran-owned small business (SDVOSB) with various regional, state, and local governmental or certifying agencies",
      "Regularly serve as outside general counsel for various privately-held businesses, providing legal advice or project management to meet their daily, varied legal and business needs",
      "Webster v. Methodist Occupational Health Centers, Inc., 141 F.3d 1236 (7th Cir. 1998)",
      "Indiana Dept. of Ins. v. Vernon General Ins. Co., 784 N.E.2d 556 (Ind. Ct. App. 2003)",
      "Sherrell v. N. Cmty. Sch. Corp. of Tipton County, 801 N.E.2d 693 (Ind. Ct. App. 2004)",
      "Allgood v. Meridian Sec. Ins. Co., 836 N.E.2d 243 (Ind. 2005)",
      "Lawler Mfg. Co. v. Bradley Corp., 2009 WL 1159577 (S.D. Ind. 2009)",
      "Hoosier Energy Rural Electric Cooperative, Inc. v. John Hancock Life Insurance Co., 582 F.3d.721 (7th Cir. 2009)",
      "In re Miller, 935 N.E.2d 729 (Ind. Ct. App. 2010)"
    ],
    "awards": [
      "Distinguished Senior Fellow, Indianapolis Bar Foundation, 2014",
      "Distinguished Fellow, Indianapolis Bar Association, 2011",
      "The Best Lawyers in America ®",
      "Business Organizations (including LLCs and Partnerships: 2026",
      "Litigation — Labor and Employment: 2026",
      "Indiana Super Lawyers®",
      "Business Litigation: 2007 – 2009, and 2021 – present"
    ],
    "barAdmissions": [
      "Indiana, 1995",
      "United States District Court for the Northern District of Indiana , 1995",
      "United States District Court for the Southern District of Indiana, 1995",
      "United States Court of Appeals for the Seventh Circuit, 1998",
      "United States Court of Appeals for the Federal Circuit , 2000"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 1994",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University, BA, _with distinction,_ 1990",
        "degree": "",
        "year": ""
      },
      {
        "institution": "National Institute for Trial Advocacy, Boulder, Colo., Graduate, 2000",
        "degree": "",
        "year": ""
      },
      {
        "institution": "ICLEF Civil Mediation Training (40 hours, Summer 2010), Graduate",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[0](https://rbelaw.com/our-team/attorneys/kathleen-hart/#)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[1](https://rbelaw.com/our-team/attorneys/kathleen-hart/#)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[2](https://rbelaw.com/our-team/attorneys/kathleen-hart/#)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "[3](https://rbelaw.com/our-team/attorneys/kathleen-hart/#)",
        "degree": "",
        "year": ""
      }
    ]
  },
  "katie-r-osborne": {
    "assistant": {
      "name": "Julie A. Adams",
      "email": "jadams@rbelaw.com"
    },
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/07/Katie-Osborne-bio-2025.pdf",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "Networking Executive Committee, 2014 – 2016",
      "Health Law Section, 2015 – present",
      "Women and the Law Division, 2016 – present",
      "Defense Trial Counsel of Indiana",
      "Health Care Section, 2015 – present",
      "Defense Research Institute"
    ],
    "representativeMatters": [
      "Obtained a defense verdict following a nine-day medical malpractice trial where the patient claimed that negligence in the recommendation for and performance of robotic radical hysterectomy for stage 1BI cervical cancer resulted in bilateral ureteral injury.",
      "Defended more than one hundred health care providers against medical malpractice claims before the Indiana Department of Insurance. Successfully obtained favorable medical review panel opinions which have led to the dismissal or abandonment of state court action.",
      "Secured dismissal for plaintiff’s failure to comply with the timeliness provisions of the Medical Malpractice Act.",
      "Respectfully advised and guided dozens of individually named health care providers through all phases of threatened or pending litigation, including depositions, mediation, and settlement, and provided guidance for completing credentialing applications.",
      "Obtained summary judgment on behalf of health care providers who have obtained favorable opinions from medical review panels.",
      "Represented dozens of health care provider clients in defense of premises liability claims involving slip and falls by visitors in/around facility.",
      "Represented manufacturing company on breach of contract action for negligent construction of facility. Case settled favorably to client.",
      "Represented business client in dispute against software development company for failure to timely deliver product pursuant to agreed specifications/timeline. Caused settled favorably to client.",
      "Represented business client in defense of a claim brought by former employee/member.",
      "Represented employer before Indiana Civil Rights Commission and secured a favorable determination from the Commission.",
      "Defended employer in enforcing restrictive covenants and confidentiality provisions of employment agreement, resulting in favorable settlement.",
      "Defended employer against age discrimination claim where employee was terminated for failing to report an accident which resulted in damage to a customer’s property. Case settled favorably for client prior to trial.",
      "Defended employer against race discrimination claim where employee was terminated for violation of attendance policy. Case settled favorably for client.",
      "Filed motion for summary judgement on plaintiff’s discrimination and wrongful termination claims, after which plaintiff’s counsel withdrew and the action was dismissed for failure to prosecute."
    ],
    "barAdmissions": [
      "Indiana, 2014",
      "United States District Court for the Northern District of Indiana, 2015",
      "United States District Court for the Southern District of Indiana, 2015"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, _cum laude,_ 2014",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University, BS, _with distinction_, 2010",
        "degree": "",
        "year": ""
      }
    ]
  },
  "katie-s-riles": {
    "assistant": {
      "name": "Rebecca D. Keever",
      "email": "bkeever@rbelaw.com"
    },
    "associations": [
      "American Bar Association",
      "Indiana State Bar Association",
      "Indianapolis Bar Association"
    ],
    "awards": [
      "Best Lawyers: Ones To Watch®",
      "Business Organizations (including LLCs and Partnerships): 2023 – present",
      "Real Estate Law: 2026",
      "Trusts and Estates: 2026",
      "Super Lawyers: Rising Stars",
      "Business / Corporate Law: 2025"
    ],
    "barAdmissions": [
      "Indiana, 2015",
      "U.S. District Court for the Northern District of Indiana, 2015",
      "U.S. District Court for the Southern District of Indiana, 2015"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, _cum laude,_ 2015",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Vanderbilt University, MEd, Organizational Leadership, 2010",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Vanderbilt University, BS, Human and Organizational Development, 2009",
        "degree": "",
        "year": ""
      }
    ]
  },
  "kevin-n-tharp": {
    "assistant": {
      "name": "Penny A. Curtis",
      "email": "pcurtis@rbelaw.com"
    },
    "associations": [
      "Construction Lawyers Society of America, Fellow, 2022 – present",
      "American Bar Association",
      "Forum on the Construction Industry and Intellectual Property Sections",
      "Indiana Bar Association",
      "Indianapolis Bar Association"
    ],
    "representativeMatters": [
      "Prosecuted patent infringement claims on behalf of table pad manufacturer. Obtained summary judgment in favor of client, in which court found that client’s patent had been infringed, and that a competitor’s patent was invalid.",
      "Obtained preliminary injunction on behalf of distributor against its former employee and competitor, enjoining them from misappropriating trade secrets.",
      "Defended consortium of pesticide distributors in a trademark opposition proceeding filed in the U.S. Patent and Trademark Office by a multi-national agribusiness company. Case settled favorably to client prior to trial.",
      "Defended internet marketing company against allegations of website content “scraping”. Case settled favorably prior to trial.",
      "Defended preliminary injunction proceeding against a manufacturer of outdoor grilling equipment in a trademark, trade dress and copyright infringement action. Preliminary injunction was denied, and case settled favorably to client.",
      "Obtained summary judgment on behalf of internet retailer against a supplier’s claims of unfair competition, defamation, and breach of contract.",
      "Prosecuted dozens of trademark applications on behalf of clients in the construction, media, manufacturing, Internet, non-profit, and technology industries.",
      "Negotiated and drafted various service and licensing agreements for provider of Internet commerce tools.",
      "Assisted software developer with its sale of software solutions to Microsoft, including the negotiation and drafting of sale and related technology development agreements",
      "Defended subcontractor against claims of misappropriation of confidential information, tortious interference with contractual relations, and unfair competition asserted by larger competitor. Obtained summary judgment in favor of client.",
      "Prosecuted UDRP actions to recover Internet domain names on behalf of international family of hotels.",
      "Pursued delay and acceleration claims on behalf of subcontractors against construction managers on large commercial projects. Claims settled through pre-suit mediations.",
      "Negotiated commercial construction subcontracts for mechanical, electrical, automation, and glass subcontractors in amounts ranging from $1 million to in excess of $100 million.",
      "Negotiated joint venture agreements among subcontractors for scopes of work ranging from $10 million to in excess of $100 million.",
      "Defended general contractor against subcontractor’s claims for payment and delays in the construction of various telecommunications facilities across the Midwest. Case settled on terms favorable to client following arbitration hearing.",
      "Prosecuted large mechanic’s lien claim against general contractor and owner, seeking payment for construction of mixed-use development. Case settled favorably to client prior to trial.",
      "Defended paving contractor against IOSHA citations arising out of trench collapse involving serious injury to client’s employee. The citations were later withdrawn.",
      "Defended paving contractor against indemnity claim brought by consulting engineer. Case settled favorably to client prior to trial.",
      "Defended national construction management firm against claims of employment discrimination pending before the Equal Employment Opportunity Commission, and in state and federal courts in multiple jurisdictions, including a defense jury verdict in federal court in Indianapolis.",
      "Asserted claims on behalf of subcontractors against payment bonds on various public projects across the State of Indiana.",
      "Defended general contractor against a subcontractor’s claims of breach of contract and anti-trust violations arising out of a bidding dispute. Case settled favorably to client prior to trial.",
      "Obtained defense verdict in favor of a contractor alleged to have negligently maintained a lift station that malfunctioned and caused damage to commercial property in excess of $1 million.",
      "Represented subsidiary of Wall Street firm in foreclosing a mortgage on an apartment complex and securing a $12 million judgment against guarantor: Ivankovich v. PAMI Grand Lake, LLC, 2009 WL 2044457 (Ind. Ct. App. 2009)",
      "Served as lead litigation counsel for lender in multi-state commercial mortgage foreclosure, and obtained favorable appellate ruling that foreclosure and other ancillary remedies were not subject to the parties’ agreement to arbitrate: Kohner Properties, Inc. v. SPCP Group VI, LLC, 408 S.W.3d 336 (Mo.App. E.D. 2013).",
      "Assisted with the sale of stock in a group of staffing companies for a purchase price in excess of $40 million.",
      "Assisted start-up with sale of its assets to a competitor for a purchase price in excess of $30 million.",
      "Assisted technology-based startup company with acquisition of patent portfolio and related assets from a venture capital group, and with raising $3 million in capital through private stock offering.",
      "Assisted family in exiting its 100-year old business through the sale of its commercial real estate, inventory and related assets, and licensure of its trademark, to a real estate developer.",
      "Assisted family with exiting its outdoor advertising business through the sale of its stock to a publicly-traded competitor.",
      "Assisted litigant with obtaining litigation financing through multi-million dollar investment in case proceeds.",
      "Assisted real estate developer with the acquisition of numerous low-income housing properties from community development corporations using federal grant proceeds.",
      "Assisted an Estate with the sale of its 50 percent interest in a closely-held manufacturing business to the surviving shareholder, the defense of claims totaling $1.7 million against the Estate arising out of the decedent’s operation of the business, and the prosecution of a six-figure claim for shareholder distributions withheld from the Estate."
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Business Organizations (including LLC’s and Partnerships): 2023 – present",
      "Commercial Litigation: 2026",
      "Construction Law: 2023 – present",
      "Litigation — Construction: 2026",
      "Indiana Super Lawyers®",
      "Construction Litigation: 2016 – present",
      "Indiana Super Lawyers Rising Star",
      "Construction Litigation: 2010 – 2015",
      "Scribe Award for Excellence in Legal Research and Writing"
    ],
    "barAdmissions": [
      "Indiana, 2000",
      "U.S. District Court for the Northern District of Indiana, 2000",
      "U.S. District Court, Southern District of Indiana, 2000",
      "U.S. District Court for the Eastern District of Michigan, 2019"
    ],
    "education": [
      {
        "institution": "Indiana University Maurer School of Law, JD, _Order of the Coif, magna cum laude,_ 2000",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Federal Communications Law Journal, Note Editor, 1999 – 2000",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University, BS, Public Affairs — Environmental Science, _with high distinction,_ 1997",
        "degree": "",
        "year": ""
      }
    ]
  },
  "laura-k-binford": {
    "assistant": {
      "name": "Lana K. Neligh",
      "email": "lneligh@rbelaw.com"
    },
    "associations": [
      "**Indianapolis Bar Association**",
      "**Defense Trial Counsel of Indiana**",
      "Medical Liability & Healthcare Law Section",
      "**Defense Research Institute**",
      "Health Law Section",
      "**American Health Lawyers Association**",
      "Healthcare Liability and Litigation and Long-Term Care, Senior Housing, In-Home Care, and Rehabilitation Sections"
    ],
    "representativeMatters": [
      "Represented hospital and residents in medical malpractice claim filed by a patient who alleged a lack of informed consent to the participation of residents in her surgery. The trial court granted summary judgment in favor of the defendant providers. The Court of Appeals affirmed and held that it was not necessary to name residents or students individually on the consent form, as the form’s generic reference to “residents” and “students” sufficed. _Tipton v. Isaacs_, 17 N.E.3d 292 (Ind. Ct. App. 2014), _trans denied_, 24 N.E.3d 967 (Ind. 2015).",
      "Represented landowner alleged to have breached duty to invitee to prevent criminal acts of third parties, in which Indiana Supreme Court affirmed grant of summary judgment in favor of landowner, on the grounds landowner did not breach duty to take reasonable steps to prevent foreseeable criminal acts against invitees: _L.W. v. Western Golf Ass’n._, 712 N.E.2d 983 (Ind. 1999)",
      "Has successfully defended health-care providers in medical malpractice actions before the Indiana Department of Insurance and in courts throughout the State of Indiana."
    ],
    "awards": [
      "Defense Trial Counsel of Indiana",
      "[Defense Lawyer of the Year, 2024](https://rbelaw.com/laura-binford-named-dtci-defense-lawyer-of-the-year/)",
      "Indiana Super Lawyers",
      "Medical Malpractice – Defense: 2022 – present",
      "The Best Lawyers in America®",
      "Health Care Law: 2026",
      "Medical Malpractice Law — Defendants: 2022 – present",
      "Indianapolis Bar Foundation",
      "Distinguished Fellow, 2015"
    ],
    "barAdmissions": [
      "Indiana (1989)",
      "U.S. District Court, Northern District of Indiana (1989)",
      "U.S. District Court, Southern District of Indiana (1989)",
      "U.S. Seventh Circuit Court of Appeals"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD (1989)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Butler University, BS (1986)",
        "degree": "",
        "year": ""
      }
    ]
  },
  "laura-s-reed": {
    "assistant": {
      "name": "Rebecca Aldous",
      "email": "baldous@rbelaw.com"
    },
    "fax": "317-955-7153",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association, Litigation Section",
      "American Bar Association",
      "Litigation, Tort and Insurance Practice Sections",
      "Defense Research Institute",
      "Defense Trial Counsel of Indiana",
      "Chair of Insurance Coverage Section, 1999"
    ],
    "representativeMatters": [
      "Represented an insurance company in a bad faith action before the Seventh Circuit Court of Appeals, which affirmed district court’s grant of summary judgment in favor of the client, on the basis that the insurer did not breach its contract or act in bad faith when it filed an interpleader against the insured and numerous claimants, and tendered its policy limits into court, and held that its duty to defend ended upon the deposit of the limits into court: Abstract & Title Guaranty Co., Inc. v. Chicago Ins. Co., 489 F.3d 808 (7th Cir. 2007).",
      "Obtained summary judgment for insured declaring that he was entitled to underinsured motorist coverage under his employer’s primary, and excess auto policies with multi-million limits for severe injuries suffered when he was hit by an uninsured motorist while assisting injured motorists: Spencer v. Liberty Mut. Ins. Co., 381 F.Supp. 2d 811 (S.D. Ind. 2005).",
      "Represented insurer in an action in which the Indiana Court of Appeals concluded there was no insurance coverage under a homeowner’s policy for injuries suffered by the insured’s minor guest when she was riding the insured’s ATV off of the insured’s property: Illinois Farmers Ins. Co. v. Wiegand, 808 N.E.2d 180 (Ind. Ct. App. 2004).",
      "Counseled and represented insurers and insureds with regard to disputes or litigation concerning liability coverage, indemnity rights, and/or the priority of coverage for construction accidents and environmental contamination.",
      "Midtown Chiropractic v. Illinois Farmers Ins. Co., 847 N.E.2d 942 (Ind. 2006)",
      "Auto Owners Ins. Co. v. United Farm Bureau Ins. Co., 560 N.E.2d 549 (Ind. Ct. App. 1990)",
      "Knight v. United Farm Bureau Ins. Co., 950 F.2d 377 (7th Cir. 1991)",
      "Hartford Fire Insurance Co. v. Pure Air, 154 F.R.D. 202 (N.D. Ind. 1993)",
      "Illinois Farmers Ins. Co. v. Adams, 144 F.3d 1129 (7th Cir. 1998)",
      "Darst v. Illinois Farmers Ins. Co., 716 N.E.2d 579 (Ind. Ct. App. 1999)",
      "Baxter v. ISTA Ins. Trust, 749 N.E.2d 47 (Ind. Ct. App. 2001)",
      "Jackson v. Jones, 804 N.E.2d 155 (Ind. Ct. App. 2004)",
      "Federated Rural Elec. Ins. Exchange v. National Farmers Union Prop. & Cas. Co., 816 N.E.2d 805 N.E.2d 456 transfer granted 816 N.E.2d 1157 (Ind. 2004)",
      "Northern Assurance Co. of America v. Thomson, Inc., 996 N.E.2d 785 (Ind. Ct. App. 2013)"
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Insurance Law: 2022 – present",
      "Litigation — Insurance: 2022 – present",
      "American Jurisprudence Awards in Civil Procedure and Family Law",
      "[Indiana Super Lawyers, 2004, 2010, and 2012 – present](https://www.superlawyers.com/indiana/lawyer/Laura-S-Reed/253177c0-c565-4d35-9916-b33c9d4eca42.html)",
      "Insurance Coverage"
    ],
    "barAdmissions": [
      "Indiana, 1987",
      "U. S. District Court for the Northern District of Indiana",
      "U.S. District Court for the Southern District of Indiana",
      "U.S. Court of Appeals for the Seventh Circuit"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, _magna cum laude_, 1987",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana Law Review, Note and Development Editor, 1986-1987",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Carleton College, BA, _magna cum laude,_ 1984",
        "degree": "",
        "year": ""
      }
    ]
  },
  "lindsay-a-llewellyn": {
    "assistant": {
      "name": "Beth A. Reis",
      "email": "breis@rbelaw.com"
    },
    "fax": "317-955-7160",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "Executive Committee of Women & the Law Division",
      "Indianapolis American Inn of Court",
      "Indianapolis Law Club",
      "ISBA Leadership Development Academy Class XI"
    ],
    "awards": [
      "Indiana State Bar Association — Leadership Development Academy Graduate, 2023",
      "The Best Lawyers in America® Ones to Watch"
    ],
    "barAdmissions": [
      "Indiana, 2015",
      "U.S. District Court for the Northern District of Indiana",
      "U.S. District Court for the Southern District of Indiana",
      "U.S. Court of Appeals for the 7th Circuit"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 2015, Certificates: Health Law, Environmental & Natural Resources Law",
        "degree": "",
        "year": ""
      },
      {
        "institution": "DePauw University, BA _cum laude_, English Literature and Latin (double major), 2011",
        "degree": "",
        "year": ""
      }
    ]
  },
  "megan-s-young": {
    "associations": [
      "Indiana, 2025",
      "United States District Court for the Northern District of Indiana, 2025",
      "United States District Court for the Southern District of Indiana, 2025"
    ],
    "barAdmissions": [
      "Indiana, 2025",
      "United States District Court for the Northern District of Indiana, 2025",
      "United States District Court for the Southern District of Indiana, 2025"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, Graduate Certificate in Health Law, _cum laude,_ 2025",
        "degree": "",
        "year": ""
      },
      {
        "institution": "University of Indianapolis, BA political science, _summa cum laude_, 2022",
        "degree": "",
        "year": ""
      }
    ]
  },
  "patrick-s-mccarney": {
    "assistant": {
      "name": "Nikki L. Viau",
      "email": "nviau@rbelaw.com"
    },
    "fax": "317-955-2175",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association"
    ],
    "awards": [
      "The Best Lawyers in America®: Ones to Watch",
      "Appellate Practice: 2026",
      "Business Organizations (including LLCs and Partnerships): 2024 – present",
      "Commercial Litigation: 2024 – present",
      "Construction Law: 2026",
      "Super Lawyers: Rising Stars — 2024",
      "Business / Corporate Law",
      "Indiana University Robert H. McKinney School of Law, 2019",
      "Chancellor’s Scholar — Awarded to the graduating student with the highest cumulative grade point average in each school at Indiana University Indianapolis",
      "Purdue University Krannert School of Management, 2019",
      "Krannert Scholar — Awarded to the top 5 percent of graduating students in each graduate cohort"
    ],
    "barAdmissions": [
      "Indiana, 2019",
      "U.S. District Court for the Northern District of Indiana, 2019",
      "U.S. District Court for the Southern District of Indiana, 2019",
      "Seventh Circuit Court of Appeals, 2020"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 2018, _summa cum laude_",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Corporate and Commercial Law Graduate Certificate",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Chancellor’s Scholar",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Purdue University Krannert School of Management, MBA, 2019, _Beta Gamma Sigma_",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Krannert Scholar",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Butler University, BA, Theatre and Political Science, 2007",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Departmental Honors in Theatre and Political Science",
        "degree": "",
        "year": ""
      }
    ]
  },
  "raymond-t-seach": {
    "assistant": {
      "name": "Nikki L. Viau",
      "email": "nviau@rbelaw.com"
    },
    "associations": [
      "Seventh Circuit Bar Association",
      "Indiana State Bar Association",
      "Indianapolis Bar Association"
    ],
    "representativeMatters": [
      "Defended an international HVAC manufacturer in its Indiana product liability and contract claims related to fires, property damages, and other losses.",
      "Represented a major CSST manufacturer in its Indiana product liability claims related to gas plumbing lines, and related fire loss claims.",
      "Obtained summary judgment or declaratory judgment in numerous large-loss construction accident, and construction defect coverage cases.",
      "Prosecuted claims by a corporation against a former employee and his business for breach of fiduciary duties, resulting in a favorable verdict at trial for the corporation.",
      "Obtained defense verdict at trial for former employees in claims by employer for alleged conversion and breach of fiduciary duties.",
      "Prosecuted claims by former business owner against the current owners for breach of fiduciary duty, which led to a significant settlement for the client.",
      "Following a significant fire, defended two jury trials against the property insurer for alleged bad faith in denying the property owners’ claim, which resulted in settlement of the claim for less than 10 percent of the alleged damages."
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Litigation — Insurance: 2022 – present",
      "Martindale-Hubbell AV Rated",
      "American Jurisprudence Award in Negotiable Instruments"
    ],
    "barAdmissions": [
      "Indiana, 1993",
      "U.S. District Court for the Northern District of Indiana, 1993",
      "U.S. District Court for the Southern District of Indiana, 1993",
      "U.S. Seventh Circuit Court of Appeals, 1993",
      "Certified Public Accountant in California (currently inactive)"
    ],
    "education": [
      {
        "institution": "Indiana University Maurer School of Law, JD, _cum laude,_ 1993",
        "degree": "",
        "year": ""
      },
      {
        "institution": "University of Notre Dame, BBA, _with High Honors,_ 1986",
        "degree": "",
        "year": ""
      }
    ]
  },
  "ryan-l-leitch": {
    "assistant": {
      "name": "Becky Keever",
      "email": "bkeever@rbelaw.com"
    },
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association"
    ],
    "beyondOffice": "Ryan enjoys spending time with his family, traveling, mentoring youth, and playing golf.",
    "representativeMatters": [
      "Represented numerous business owners in the organization, formation, funding, sale, purchase or merger of their businesses, and in the preparation of various types of business contracts and agreements.",
      "Prepared numerous estate and business succession plans to assist clients in achieving their objectives, whether it be to pass their businesses on to their children or otherwise.",
      "Assisted numerous clients in the administration of trusts and the estate probate process.",
      "Assisted numerous clients with preparation of their wills and trusts, to accomplish their estate planning goals.",
      "Represented construction contractors in negotiating contracts, handling lien claims, and resolving other construction-related disputes.",
      "Served as lead counsel for a large hedge fund in a series of complex, multi-million-dollar business workouts and related business transactions.",
      "Recovered a total of approximately $100 million on behalf of a Fortune 500 client through the enforcement of a series of loan guarantees."
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Commercial Litigation: 2023 – present",
      "Litigation: Construction: 2026",
      "Real Estate Law: 2023 – present",
      "Martindale-Hubbell – AV Preeminent Rated: 2013 – present",
      "Indianapolis Bar Foundation, Distinguished Fellow",
      "Indiana Super Lawyers",
      "Business and Corporate: 2013 – present",
      "Mergers and Acquisitions: 2013 – present",
      "Estate Planning and Probate: 2013 – present"
    ],
    "barAdmissions": [
      "Indiana, 1987",
      "U.S. District Court, Northern District of Indiana",
      "U.S. District Court, Southern District of Indiana",
      "United States Court of Appeals for the Seventh Circuit",
      "United States Supreme Court"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 1987",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University, BS, Finance, 1984",
        "degree": "",
        "year": ""
      }
    ]
  },
  "sarah-macgill-marr": {
    "assistant": {
      "name": "Penny A. Curtis",
      "email": "pcurtis@rbelaw.com"
    },
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/11/Sarah-Marr-Bio-for-Print-9-19-25-pdf.pdf",
    "associations": [
      "American Bar Association",
      "Indiana State Bar Association",
      "Indianapolis Bar Association",
      "Defense Trial Counsel of Indiana",
      "Defense Research Institute"
    ],
    "representativeMatters": [
      "Successfully defended multi-million dollar property damage claims brought by a municipal entity against our client for negligence and breach of contract as well as cross-claims brought by other parties against our client. Case was favorably resolved prior to trial.",
      "Defended general contractor at bench trial where allegations included claims that the contractor had extensively damaged property off the project site. Obtained favorable result on behalf of our client.",
      "Defended engineering firm in matter involving multiple fatalities where the allegations included negligence and breach of other professional duties. Matter was resolved prior to trial.",
      "Defended subcontractor in connection with large claims for negligence and breach of contract relating to construction of a large multi-family housing unit. Case settled favorably prior to trial.",
      "Defended product manufacturer in litigation involving claims that a consumer appliance was defective where damages exceeded $1 million.",
      "Defended product manufacturer in significant matter in Federal Court where allegations included claims for a defective appliance product and damages significantly exceeded expected values. Matter was favorably resolved prior to trial.",
      "Defended large corporate entity against allegations of breach of fiduciary duty, fraud, deception, and conversion brought by one shareholder of the corporate entity against the other shareholder and the entity itself. Prosecuted claims for fraud, conversion, breach of contract, and contribution against one of the shareholders. Case settled favorably prior to trial.",
      "Defended national event promotor in the motorsports industry wherein a team asserted claims against another team, a sponsor, as well as our client.  Secured Summary Judgment in favor of our client on all pending claims against it.",
      "Represented corporate entity in a case where the minority shareholder asserted claims against the majority shareholder and ultimately sought a court-ordered buyout of the minority shares. Matter was favorably resolved prior to Court intervention.",
      "Lead trial counsel in matter involving a dispute following the purchase of real estate in southern Indiana.",
      "Defended General Contractor during proceedings involving damage to residential real estate.",
      "Part of team representing a client in front of the United States Court of Appeals for the Seventh Circuit.",
      "Sarah regularly volunteers with the Southern District of Indiana Pro Bono Program.",
      "Represented an incarcerated individual in connection with his claims asserted pursuant to the Eighth Amendment of the Constitution of the United States of America.",
      "Represented an incarcerated individual in connection with his efforts to collect a judgment following the Court’s entry of Summary Judgment in his favor."
    ],
    "awards": [
      "IBJ Forty Under 40, 2022",
      "[READ IBJ FORTY UNDER 40 PROFILE](https://rbelaw.com/wp-content/uploads/2022/03/Marr.pdf)",
      "The Best Lawyers in America®",
      "Commercial Litigation: 2022 – present",
      "Construction Law: 2022 – present",
      "Insurance Law: 2022 – present",
      "Litigation — Construction: 2026",
      "Litigation — Insurance: 2026",
      "Product Liability Litigation — Defendants: 2022 – present",
      "Indiana Super Lawyers, 2024",
      "Business Litigation",
      "Indiana Super Lawyers Rising Star",
      "Business Litigation: 2014 – 2023",
      "Order of the Barristers",
      "Indiana University Robert H. McKinney School of Law, 2007 – 2008"
    ],
    "barAdmissions": [
      "Indiana, 2009",
      "U.S. District Court for the Northern District of Indiana",
      "U.S. District Court for the Southern District of Indiana",
      "U.S. Court of Appeals for the 7th Circuit",
      "D.C. Court of Appeals"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, 2008",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University, BS, Marketing and International Business, Minor in Spanish, 2005",
        "degree": "",
        "year": ""
      }
    ]
  },
  "timothy-h-button": {
    "assistant": {
      "name": "Rebecca D. Keever",
      "email": "bkeever@rbelaw.com"
    },
    "fax": "317-955-7178",
    "bioPdfUrl": "https://rbelaw.com/wp-content/uploads/2025/08/Tim-Button-Bio-8-28-2025.pdf",
    "associations": [
      "Indianapolis Bar Association",
      "Indiana State Bar Association"
    ],
    "representativeMatters": [
      "Represented major hospital corporation before the Metropolitan Development Commission to secure zoning variances and approvals for multiple development projects across multiple hospital campuses.",
      "Negotiated and reviewed numerous commercial leases in multiple states for a leading provider of cell phone services.",
      "Counsel to numerous start-up business entities and emerging businesses, including one of the “Inc. 500” _Fastest Growing Private Companies in the United States_.",
      "Negotiated favorable settlements with client’s former employees who violated their non-compete agreements.",
      "Counsel to multi-billion-dollar hedge fund on creditors rights matters including foreclosure proceedings, negotiation of forbearance agreements, and restructuring of debtor obligations."
    ],
    "awards": [
      "The Best Lawyers in America®",
      "Real Estate Law: 2025 – present",
      "Indiana Super Lawyers Rising Star: 2013 – 2014",
      "National Moot Court Team (National Security Law): 2004",
      "Dean Normal Lefstein Award for Pro Bono Service, Indiana University Indianapolis McKinney School of Law"
    ],
    "barAdmissions": [
      "Indiana (2004)",
      "U.S. District Court for the Northern District of Indiana",
      "U.S. District Court for the Southern District of Indiana"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD (2004)",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Hamilton College, AB (1989)",
        "degree": "",
        "year": ""
      }
    ]
  },
  "travis-r-watson": {
    "assistant": {
      "name": "Beth A. Reis",
      "email": "breis@rbelaw.com"
    },
    "fax": "317-955-7147",
    "associations": [
      "Indiana State Bar Association",
      "Indianapolis Bar Association"
    ],
    "beyondOffice": "Travis lives in Zionsville with his wife, daughter, and two dogs. In his free time, he enjoys going on road trips, attending concerts, watching the Yankees, and going on hikes with his dogs around Indiana parks. Travis and his family are in the process of attending a game at every MLB stadium (so far, they’ve been to 12/30).",
    "barAdmissions": [
      "Indiana, 2020",
      "U.S. District Court for the Northern District of Indiana, 2020",
      "U.S. District Court for the Southern District of Indiana, 2020"
    ],
    "education": [
      {
        "institution": "Indiana University Robert H. McKinney School of Law, JD, _summa cum laude_, 2020",
        "degree": "",
        "year": ""
      },
      {
        "institution": "Indiana University Kelley School of Business, BS, Marketing and Supply Chain Management, 2015",
        "degree": "",
        "year": ""
      }
    ]
  }
} as const
