/**
 * Blog image mapping (slug -> local image path).
 *
 * Auto-generated by `scripts/download-blog-images.ts`.
 * Do not edit by hand.
 */

export const blogImageBySlug: Record<string, string> = {
  "carmel-based-firm-uncovers-three-separate-cases-of-employee-fraud": "/images/newsroom/cc7ccc8132-Kouns_Doug_mug.webp"
} as const
