/**
 * Blog taxonomy mapping (slug -> categories/tags).
 *
 * Auto-generated by `scripts/generate-blog-taxonomy.ts`.
 * Do not edit by hand.
 */

export const blogTaxonomyBySlug: Record<string, { categories: string[]; tags: string[] }> = {
  "11-tips-to-maximize-the-value-of-your-lawyer": {
    "categories": [],
    "tags": []
  },
  "2019-cultural-trail-spring-clean": {
    "categories": [],
    "tags": []
  },
  "2025-super-lawyers-honorees": {
    "categories": [],
    "tags": []
  },
  "2026-best-law-firms": {
    "categories": [],
    "tags": []
  },
  "2026-best-lawyers": {
    "categories": [],
    "tags": []
  },
  "4-things-to-consider-when-forming-your-entity-online": {
    "categories": [],
    "tags": []
  },
  "5-common-mistakes-made-by-construction-project-managers-and-how-to-avoid-them": {
    "categories": [],
    "tags": []
  },
  "5-key-considerations-when-seeking-a-trademark": {
    "categories": [],
    "tags": []
  },
  "5-problems-of-success-managing-construction-contractors-through-covid-19-and-beyond": {
    "categories": [],
    "tags": []
  },
  "5-reasons-to-complete-your-estate-plans-today": {
    "categories": [],
    "tags": []
  },
  "7-questions-to-ask-before-appealing": {
    "categories": [],
    "tags": []
  },
  "7-tips-to-help-you-handle-your-first-jury-trial": {
    "categories": [],
    "tags": []
  },
  "9-tips-for-a-successful-deposition": {
    "categories": [],
    "tags": []
  },
  "a-potential-business-pipeline-government-contract-awards": {
    "categories": [],
    "tags": []
  },
  "a-tenants-options-when-leased-space-is-no-longer-wanted": {
    "categories": [],
    "tags": []
  },
  "ai-and-copyright-fair-use": {
    "categories": [],
    "tags": []
  },
  "ai-and-copyright-law-ruling-26-june-2025": {
    "categories": [],
    "tags": []
  },
  "ai-privacy-implicated-in-court-ruling": {
    "categories": [],
    "tags": []
  },
  "ais-impact-from-driverless-cars-to-lawyerless-law-firms": {
    "categories": [],
    "tags": []
  },
  "alert-cta-injunction-reinstated": {
    "categories": [],
    "tags": []
  },
  "are-medical-providers-entitled-to-reasonable-payment-for-their-time-participating-in-a-deposition": {
    "categories": [],
    "tags": []
  },
  "are-you-adequately-insured-a-primer-about-personal-casualty-and-commercial-insurance-coverages": {
    "categories": [],
    "tags": []
  },
  "attorney-anna-marvin-joins-rbe": {
    "categories": [],
    "tags": []
  },
  "attorney-client-privilege-and-business-entities-will-your-attorney-client-communications-be-protected": {
    "categories": [],
    "tags": []
  },
  "attorney-j-t-wynne-joins-rbe": {
    "categories": [],
    "tags": []
  },
  "attorney-lindsay-llewellyn-joins-rbe": {
    "categories": [],
    "tags": []
  },
  "attorney-mark-mckinzie-retires": {
    "categories": [],
    "tags": []
  },
  "attorney-tony-jost-speaks-about-the-election-process-in-the-classroom": {
    "categories": [],
    "tags": []
  },
  "avoiding-hiccups-with-hica-indianas-home-improvement-contract-act": {
    "categories": [],
    "tags": []
  },
  "best-lawyers-recognizes-22-rbe-attorneys": {
    "categories": [],
    "tags": []
  },
  "boi-filing-not-required-for-u-s-citizens-domestic-entities": {
    "categories": [],
    "tags": []
  },
  "bryce-bennett-founding-partner-of-riley-bennett-egloff-to-retire-after-45-years": {
    "categories": [],
    "tags": []
  },
  "business-structures-explained": {
    "categories": [],
    "tags": []
  },
  "buying-a-business-or-buying-trouble-4-tips-to-minimize-risk": {
    "categories": [],
    "tags": []
  },
  "can-subcontractors-recover-their-attorneys-fees-from-general-contractors-under-indianas-mechanics-lien-act": {
    "categories": [],
    "tags": []
  },
  "cant-we-just-appeal-when-and-when-not-to-seek-an-appeal": {
    "categories": [],
    "tags": []
  },
  "cares-act-business-loans-available-covid-19": {
    "categories": [],
    "tags": []
  },
  "carmel-based-firm-uncovers-three-separate-cases-of-employee-fraud": {
    "categories": [],
    "tags": []
  },
  "caught-between-a-rock-and-a-hard-place-the-perils-of-simultaneously-defending-against-criminal-and-civil-lawsuits": {
    "categories": [],
    "tags": []
  },
  "choosing-the-right-type-of-buy-sell-agreement-for-your-business": {
    "categories": [],
    "tags": []
  },
  "closing-mergers-and-acquisitions-the-importance-of-disclosure-schedules": {
    "categories": [],
    "tags": []
  },
  "collections-101-what-you-need-to-know": {
    "categories": [],
    "tags": []
  },
  "common-mistakes-made-by-small-business-owners": {
    "categories": [],
    "tags": []
  },
  "congratulations-elizabeth-green-and-tony-jost": {
    "categories": [],
    "tags": []
  },
  "congratulations-to-rbes-2022-super-lawyers": {
    "categories": [],
    "tags": []
  },
  "congratulations-to-rbes-2023-super-lawyers": {
    "categories": [],
    "tags": []
  },
  "construction-lien-waivers-signers-beware": {
    "categories": [],
    "tags": []
  },
  "copyright-law-and-the-monument-industry-does-my-monument-design-infringe-a-copyright": {
    "categories": [],
    "tags": []
  },
  "corporate-transparency-act-what-you-need-to-know-right-now": {
    "categories": [],
    "tags": []
  },
  "court-vacates-salary-threshold-for-exempt-status": {
    "categories": [],
    "tags": []
  },
  "covid-19-business-resource-developments": {
    "categories": [],
    "tags": []
  },
  "covid-19-changes-that-may-be-here-to-stay": {
    "categories": [],
    "tags": []
  },
  "covid-19-insurance-claims-update": {
    "categories": [],
    "tags": []
  },
  "creditors-rights-when-a-debtor-is-threatening-to-file-bankruptcy": {
    "categories": [],
    "tags": []
  },
  "cta-new-final-interim-rule": {
    "categories": [],
    "tags": []
  },
  "death-of-an-expert-witness-what-happens-next": {
    "categories": [],
    "tags": []
  },
  "do-i-need-a-will-what-is-a-trust-do-i-need-to-do-any-estate-planning": {
    "categories": [],
    "tags": []
  },
  "does-my-business-need-or-need-to-update-a-buy-sell-agreement": {
    "categories": [],
    "tags": []
  },
  "don-smith-has-been-elected-president-elect-of-the-defense-trial-counsel-of-indiana": {
    "categories": [],
    "tags": []
  },
  "dont-cash-that-check-the-pitfalls-of-accord-and-satisfaction": {
    "categories": [],
    "tags": []
  },
  "dram-shop-liability-is-not-just-for-bars-take-care-when-serving-alcohol": {
    "categories": [],
    "tags": []
  },
  "eight-things-to-know-before-using-a-golf-cart-on-a-street-in-indiana": {
    "categories": [],
    "tags": []
  },
  "eleven-riley-bennett-egloff-attorneys-named-2019-super-lawyers-and-rising-stars": {
    "categories": [],
    "tags": []
  },
  "employee-handbooks-one-size-does-not-fit-all": {
    "categories": [],
    "tags": []
  },
  "employers-beware-you-may-be-the-next-union-target": {
    "categories": [],
    "tags": []
  },
  "employers-need-to-proceed-cautiously-when-settling-employee-claims": {
    "categories": [],
    "tags": []
  },
  "employment-law-alert-supreme-court-decision-lightens-employer-burden-in-flsa-disputes": {
    "categories": [],
    "tags": []
  },
  "employment-noncompete-agreements-under-attack": {
    "categories": [],
    "tags": []
  },
  "engage-cost-effective-legal-counsel": {
    "categories": [],
    "tags": []
  },
  "eric-hylton-distinguished-fellows": {
    "categories": [],
    "tags": []
  },
  "farewell-and-best-wishes-beth-green": {
    "categories": [],
    "tags": []
  },
  "federal-district-court-issues-nationwide-injunction": {
    "categories": [],
    "tags": []
  },
  "federal-trade-commission-takes-step-to-ban-most-non-compete-agreements-nationwide": {
    "categories": [],
    "tags": []
  },
  "financial-assistance-resources-for-businesses-affected-by-covid-19": {
    "categories": [],
    "tags": []
  },
  "fire-and-arson-scene-evidence-the-importance-of-proper-evidence-collection": {
    "categories": [],
    "tags": []
  },
  "five-mistakes-subcontractors-commonly-make-before-signing-construction-subcontracts": {
    "categories": [],
    "tags": []
  },
  "five-reasons-why-you-should-involve-your-attorneys-early-in-your-business-transactions": {
    "categories": [],
    "tags": []
  },
  "flsa-salary-tests": {
    "categories": [],
    "tags": []
  },
  "foreign-corrupt-practices-act": {
    "categories": [],
    "tags": []
  },
  "fourteen-riley-bennett-egloff-attorneys-named-2020-super-lawyers-and-rising-stars": {
    "categories": [],
    "tags": []
  },
  "generative-ais-conflicts-with-copyright-law": {
    "categories": [],
    "tags": []
  },
  "gwds-appellate-courts-limit-damages": {
    "categories": [],
    "tags": []
  },
  "happy-spring-time-to-sue-my-service-provider-or-disparage-my-neighbor": {
    "categories": [],
    "tags": []
  },
  "hart-trade-secret-protection-requires-customized-measures": {
    "categories": [],
    "tags": []
  },
  "health-care-providers-may-not-be-held-liable-for-computer-errors-with-electronic-medical-records": {
    "categories": [],
    "tags": []
  },
  "house-enrolled-act-1593": {
    "categories": [],
    "tags": []
  },
  "how-does-indianas-medical-review-panel-process-work": {
    "categories": [],
    "tags": []
  },
  "how-indiana-is-improving-school-safety-security": {
    "categories": [],
    "tags": []
  },
  "how-to-avoid-liability-for-being-a-good-citizen": {
    "categories": [],
    "tags": []
  },
  "ibj-article-recalls-1996-event-where-president-trump-was-roasted": {
    "categories": [],
    "tags": []
  },
  "immunity-for-healthcare-providers-during-covid-19-crisis": {
    "categories": [],
    "tags": []
  },
  "indiana-court-of-appeals-upholds-employers-noncompete": {
    "categories": [],
    "tags": []
  },
  "indiana-makes-significant-changes-to-end-of-life-health-care-decisions-and-medical-consent-laws": {
    "categories": [],
    "tags": []
  },
  "indiana-spoliation-law-experts-can-be-critical-and-good-faith-may-not-be-enough": {
    "categories": [],
    "tags": []
  },
  "indiana-supreme-court-2024-commentary-on-deliberate-indifference-standard-in-correctional-litigation": {
    "categories": [],
    "tags": []
  },
  "indiana-supreme-court-issues-decision-impacting-employment-agreements": {
    "categories": [],
    "tags": []
  },
  "indianas-duty-to-immediately-report-child-abuse": {
    "categories": [],
    "tags": []
  },
  "indianas-personal-liability-notice-and-subcontractors": {
    "categories": [],
    "tags": []
  },
  "indianas-wrongful-death-damages-a-cheat-sheet-for-what-damages-are-recoverable": {
    "categories": [],
    "tags": []
  },
  "injunction-suspends-enforcement-cta": {
    "categories": [],
    "tags": []
  },
  "insurers-take-note-the-effect-of-recent-decisions-applying-indianas-um-uim-statute-to-commercial-excess-and-umbrella-policies": {
    "categories": [],
    "tags": []
  },
  "is-an-in-house-counsel-position-right-for-you": {
    "categories": [],
    "tags": []
  },
  "is-an-indiana-series-llc-right-for-my-next-business": {
    "categories": [],
    "tags": []
  },
  "is-the-definition-of-a-work-related-accident-being-changed": {
    "categories": [],
    "tags": []
  },
  "jaclyn-flint-honored-as-up-and-coming-lawyer": {
    "categories": [],
    "tags": []
  },
  "jaclyn-flint-promoted-to-partner": {
    "categories": [],
    "tags": []
  },
  "justin-sorrell-selected-to-participate-in-the-indiana-state-bar-associations-leadership-development-academy": {
    "categories": [],
    "tags": []
  },
  "landlords-may-be-liable-for-tenant-on-tenant-harassment": {
    "categories": [],
    "tags": []
  },
  "laura-binford-named-dtci-defense-lawyer-of-the-year": {
    "categories": [],
    "tags": []
  },
  "lease-negotiations-tips-for-tenants": {
    "categories": [],
    "tags": []
  },
  "legal-500-elite-2025": {
    "categories": [],
    "tags": []
  },
  "legal-risks-of-ai-in-medicine": {
    "categories": [],
    "tags": []
  },
  "limited-liability-for-owners-of-corporations-and-llcs-what-liabilities-and-what-limits": {
    "categories": [],
    "tags": []
  },
  "litigation-hold-letters-5-steps-to-avoid-problems": {
    "categories": [],
    "tags": []
  },
  "medical-malpractice-claims-arising-out-of-covid-19-does-the-immunity-provision-achieve-its-intended-purpose": {
    "categories": [],
    "tags": []
  },
  "medical-malpractice-or-ordinary-negligence-a-primer-for-understanding-the-scope-and-impact-of-the-medical-malpractice-act": {
    "categories": [],
    "tags": []
  },
  "megan-young-joins-firm": {
    "categories": [],
    "tags": []
  },
  "minimizing-covid-risks-to-your-business-release-and-indemnity-agreements": {
    "categories": [],
    "tags": []
  },
  "navigating-indianas-medical-malpractice-act-statute-of-limitations": {
    "categories": [],
    "tags": []
  },
  "navigating-payment-disputes-on-public-construction-projects": {
    "categories": [],
    "tags": []
  },
  "negotiation-skills-from-poker": {
    "categories": [],
    "tags": []
  },
  "new-ai-copyright-lawsuit-filed": {
    "categories": [],
    "tags": []
  },
  "new-ftc-noncompete-rule-may-change-the-employment-landscape": {
    "categories": [],
    "tags": []
  },
  "new-rbe-associate-jaclyn-flint": {
    "categories": [],
    "tags": []
  },
  "nil-development-in-amateur-sports": {
    "categories": [],
    "tags": []
  },
  "nineteen-rbe-attorneys-recognized-as-best-lawyers-in-america-2023": {
    "categories": [],
    "tags": []
  },
  "overtime-update-u-s-department-of-labors-new-mandatory-overtime-pay-rule-effective-jan-1": {
    "categories": [],
    "tags": []
  },
  "partner-tony-jost-on-being-elected-vice-president-of-program-for-the-crossroads-of-america-council-on-its-executive-committee": {
    "categories": [],
    "tags": []
  },
  "paycheck-protection-program-guidance-and-resources-covid-19": {
    "categories": [],
    "tags": []
  },
  "petitioning-for-modification-or-withdrawal-of-the-probationary-status-of-an-indiana-license": {
    "categories": [],
    "tags": []
  },
  "planning-your-retirement-destination": {
    "categories": [],
    "tags": []
  },
  "playing-for-pay-recent-issues-surrounding-compensation-for-use-of-student-athletes-names-images-and-likenesses": {
    "categories": [],
    "tags": []
  },
  "prepare-for-a-successful-mediation": {
    "categories": [],
    "tags": []
  },
  "professional-licensing-litigation-how-to-use-pre-hearing-settlement-conferences-to-your-advantage": {
    "categories": [],
    "tags": []
  },
  "protect-yourself-by-understanding-the-basics-indemnity-agreements-insurance-procurement-and-additional-insured-endorsements": {
    "categories": [],
    "tags": []
  },
  "protecting-your-business-does-your-non-compete-agreement-stand-the-test-of-time": {
    "categories": [],
    "tags": []
  },
  "protecting-your-businesss-invisible-assets": {
    "categories": [],
    "tags": []
  },
  "rbe-attorney-courtney-mills-presented-oral-argument-before-the-indiana-supreme-court": {
    "categories": [],
    "tags": []
  },
  "rbe-attorney-katie-osborne-was-selected-to-participate-in-the-indiana-state-bar-associations-leadership-development-academy-for-2017": {
    "categories": [],
    "tags": []
  },
  "rbe-attorney-sarah-macgill-marr-nominated-to-ibj-2022-forty-under-40": {
    "categories": [],
    "tags": []
  },
  "rbe-attorneys-named-super-lawyers": {
    "categories": [],
    "tags": []
  },
  "rbe-celebrates-its-40th-anniversary-by-participating-in-the-united-way-kit-build-program": {
    "categories": [],
    "tags": []
  },
  "rbe-celebrating-40-years": {
    "categories": [],
    "tags": []
  },
  "rbe-helps-operation-school-bell-more-books-are-needed": {
    "categories": [],
    "tags": []
  },
  "rbe-is-pleased-to-announce-our-new-partners-2": {
    "categories": [],
    "tags": []
  },
  "rbe-is-pleased-to-announcement-our-new-partners": {
    "categories": [],
    "tags": []
  },
  "rbe-magzine-july-2021": {
    "categories": [],
    "tags": []
  },
  "rbe-participates-in-salvation-armys-angel-tree-program": {
    "categories": [],
    "tags": []
  },
  "rbe-partner-anthony-jost-appointed-to-uwci-capital-projects-fund-committee": {
    "categories": [],
    "tags": []
  },
  "rbe-partner-tony-jost-receives-silver-beaver-award-from-the-boy-scouts-of-america": {
    "categories": [],
    "tags": []
  },
  "rbe-reached-100-participation-in-the-indiana-university-robert-h-mckinney-school-of-law-2018-law-firm-and-corporate-campaign": {
    "categories": [],
    "tags": []
  },
  "rbe-recognized-among-best-law-firms": {
    "categories": [],
    "tags": []
  },
  "rbe-sponsors-ibjs-forty-under-40-reception": {
    "categories": [],
    "tags": []
  },
  "rbe-staff-participated-in-the-indianapolis-cultural-trail-spring-cleanup": {
    "categories": [],
    "tags": []
  },
  "rbe-supports-ace-mentor-program": {
    "categories": [],
    "tags": []
  },
  "ready-or-not-updates-to-indianas-medical-malpractice-act-are-headed-your-way": {
    "categories": [],
    "tags": []
  },
  "renewing-your-indiana-professional-license-and-attending-a-personal-appearance-hearing": {
    "categories": [],
    "tags": []
  },
  "responding-to-inadvertent-disclosures-of-employee-and-consumer-personal-information": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-announces-2024-best-lawyers-honorees": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-announces-2024-super-lawyers-honorees": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-announces-retirement-of-john-l-egloff": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-attorneys-participate-in-the-ask-a-lawyer-program": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-llp-attorneys-participate-in-the-ask-a-lawyer-program": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-recognized-among-best-law-firms": {
    "categories": [],
    "tags": []
  },
  "riley-bennett-egloff-welcomes-attorney-beau-browning": {
    "categories": [],
    "tags": []
  },
  "safeguard-your-secrets-to-protect-your-companys-future": {
    "categories": [],
    "tags": []
  },
  "salary-test-ruled-unlawful": {
    "categories": [],
    "tags": []
  },
  "sba-updates-guidance-on-the-necessity-certification-for-ppp-loans": {
    "categories": [],
    "tags": []
  },
  "scooter-users-beware-liability-and-insurance-implications-for-consumers": {
    "categories": [],
    "tags": []
  },
  "scotus-accepts-indiana-nursing-home-case": {
    "categories": [],
    "tags": []
  },
  "seventeen-riley-bennett-egloff-attorneys-named-2021-super-lawyers-and-rising-stars": {
    "categories": [],
    "tags": []
  },
  "should-an-employer-contest-claims-for-unemployment-compensation-benefits": {
    "categories": [],
    "tags": []
  },
  "should-your-llc-change-its-operating-agreement-to-address-2018-tax-law-changes": {
    "categories": [],
    "tags": []
  },
  "six-tenant-tips-for-leasing-space": {
    "categories": [],
    "tags": []
  },
  "smith-your-old-noncompete-form-agreement-may-miss-the-mark": {
    "categories": [],
    "tags": []
  },
  "sometimes-form-is-substance-appellate-rules-can-be-complex-and-difficult-to-navigate": {
    "categories": [],
    "tags": []
  },
  "summary-medical-license-suspensions-high-stakes-low-due-process-requirements": {
    "categories": [],
    "tags": []
  },
  "tales-from-the-trail-meet-bryce-bennett": {
    "categories": [],
    "tags": []
  },
  "tariffs-impact-construction-industry": {
    "categories": [],
    "tags": []
  },
  "temporary-block-on-oshas-emergency-temporary-standard": {
    "categories": [],
    "tags": []
  },
  "the-business-entity-harmonization-act-in-30-seconds-or-less": {
    "categories": [],
    "tags": []
  },
  "the-consumer-complaint-investigative-process-at-the-office-of-the-indiana-attorney-general": {
    "categories": [],
    "tags": []
  },
  "the-department-of-labor-issues-regulations-implementing-new-leave-of-absence-law": {
    "categories": [],
    "tags": []
  },
  "the-first-five-things-to-do-after-being-sued": {
    "categories": [],
    "tags": []
  },
  "the-hidden-legal-impact-of-new-rules-for-lease-accounting": {
    "categories": [],
    "tags": []
  },
  "the-indiana-state-bar-association-futures-committee": {
    "categories": [],
    "tags": []
  },
  "the-long-arm-of-the-law-or-how-to-pull-out-of-state-opponents-into-court": {
    "categories": [],
    "tags": []
  },
  "the-rise-of-sports-betting-in-indiana-and-the-challenges-it-faces": {
    "categories": [],
    "tags": []
  },
  "the-top-5-mistakes-made-by-start-up-businesses": {
    "categories": [],
    "tags": []
  },
  "the-workers-compensation-act-changes-again-on-january-1-2019": {
    "categories": [],
    "tags": []
  },
  "the-workers-compensation-act-changes-july-1": {
    "categories": [],
    "tags": []
  },
  "thirteen-rbe-attorneys-recognized-in-the-best-lawyers-in-america-2022": {
    "categories": [],
    "tags": []
  },
  "three-areas-of-legal-risk-to-address-early-and-often": {
    "categories": [],
    "tags": []
  },
  "three-lessons-learned-from-law-firm-partnership-divorces": {
    "categories": [],
    "tags": []
  },
  "time-for-change-again-increasing-limits-under-indianas-medical-malpractice-act": {
    "categories": [],
    "tags": []
  },
  "time-for-change-proposed-amendments-to-indianas-medical-malpractice-act": {
    "categories": [],
    "tags": []
  },
  "tis-the-seasonto-review-your-restrictive-employment-agreements": {
    "categories": [],
    "tags": []
  },
  "twelve-riley-bennett-egloff-attorneys-named-2018-super-lawyers-and-rising-stars": {
    "categories": [],
    "tags": []
  },
  "two-steps-you-can-take-today-to-protect-yourself-and-your-loved-ones-in-these-uncertain-times": {
    "categories": [],
    "tags": []
  },
  "u-s-department-of-labor-announcement": {
    "categories": [],
    "tags": []
  },
  "u-s-supreme-court-decisions-on-covid-19-vaccine-mandates": {
    "categories": [],
    "tags": []
  },
  "understanding-and-carrying-out-a-loved-ones-wishes-and-plans-for-incapacity": {
    "categories": [],
    "tags": []
  },
  "understanding-your-intellectual-property": {
    "categories": [],
    "tags": []
  },
  "undocumented-workers-injury-suit-puts-major-issues-before-justices": {
    "categories": [],
    "tags": []
  },
  "update-fifth-circuits-stay-on-oshas-covid-19-vaccination-and-testing-regulations": {
    "categories": [],
    "tags": []
  },
  "update-indianas-wrongful-death-damages-a-cheat-sheet-for-what-damages-are-recoverable": {
    "categories": [],
    "tags": []
  },
  "what-does-the-liability-section-of-your-homeowners-policy-cover": {
    "categories": [],
    "tags": []
  },
  "what-indiana-employers-need-to-know-when-settling-workers-compensation-claims": {
    "categories": [],
    "tags": []
  },
  "what-makes-a-plaintiff-whole-patchett-v-lees-impact-on-medical-special-valuation": {
    "categories": [],
    "tags": []
  },
  "who-may-obtain-a-protective-order": {
    "categories": [],
    "tags": []
  },
  "why-cant-we-all-just-work-together-a-client-centered-approach-to-working-with-business-advisors": {
    "categories": [],
    "tags": []
  },
  "why-you-should-complete-or-update-your-estate-plans-today": {
    "categories": [],
    "tags": []
  },
  "working-with-idoi-yields-favorable-results-for-rbe-clients": {
    "categories": [],
    "tags": []
  },
  "workplace-covid-19-exposure-and-infection-claims-what-employers-need-to-know": {
    "categories": [],
    "tags": []
  },
  "xbe-mbe-wbe-vbe-dbe-a-path-of-opportunity-for-your-business": {
    "categories": [],
    "tags": []
  },
  "you-can-bet-on-it-sports-gambling-legislation-in-indiana-and-beyond": {
    "categories": [],
    "tags": []
  },
  "you-received-a-consumer-complaint-from-the-office-of-the-indiana-attorney-general-now-what": {
    "categories": [],
    "tags": []
  },
  "youre-ready-to-settle-that-workers-comp-case-so-now-what": {
    "categories": [],
    "tags": []
  }
} as const
