// Auto-generated by scripts/fetch-practice-area-headers.ts
export interface HeroImage { src: string; srcset: string; credit?: string }
export const practiceAreaHeroes: Record<string, HeroImage> = {
  "business-law": {
    "src": "/assets/practice-areas/business-law-1920.webp",
    "srcset": "/assets/practice-areas/business-law-1024.webp 1024w, /assets/practice-areas/business-law-1536.webp 1536w, /assets/practice-areas/business-law-1920.webp 1920w",
    "credit": "Neon Wang"
  },
  "bankruptcy-reorganization": {
    "src": "/assets/practice-areas/bankruptcy-reorganization-1920.webp",
    "srcset": "/assets/practice-areas/bankruptcy-reorganization-1024.webp 1024w, /assets/practice-areas/bankruptcy-reorganization-1536.webp 1536w, /assets/practice-areas/bankruptcy-reorganization-1920.webp 1920w",
    "credit": "Cheung Yin"
  }
} as const;
export function getPracticeAreaHero(slug: string): HeroImage | undefined { return practiceAreaHeroes[slug]; }
