// Auto-generated by scripts/fetch-practice-area-headers.ts
export interface HeroImage { src: string; srcset: string; credit?: string }
export const practiceAreaHeroes: Record<string, HeroImage> = {} as const;
export function getPracticeAreaHero(slug: string): HeroImage | undefined { return practiceAreaHeroes[slug]; }
